package rb.hsv.appendix.ccd.valid;

import java.io.File;

import static rb.hsv.appendix.ccd.valid.util.ValidUtil.isValidVerse;

public class ValidWijzen {

    public static boolean isValid(final String keyArg, final String arg, final File curFile, final String vs) {
        return switch (keyArg) {
            case "aanwijzen" -> isAanwijzen(curFile, vs);
            case "afwijzen" -> isAfwijzen(curFile, vs);
            case "terechtwijzen" -> isTerechtwijzen(curFile, vs);
            case "toewijzen" -> isToewijzen(curFile, vs);
            case "wees" -> isWees(curFile, vs);
            case "wezen" -> isWezen(curFile, vs, arg);
            case "wijs" -> isWijs(curFile, vs);
            case "wijze (manier)" -> isWijzeManier(curFile, vs);
            case "wijze (persoon)" -> isWijzePersoon(curFile, vs);
            case "wijzen" -> isWijzen(curFile, vs, arg);
            default -> true;
        };
    }

    private static boolean isAanwijzen(final File curFile, final String vs) {
        return isValidVerse(curFile, vs, "Josh-07.html#vs17")
                || isValidVerse(curFile, vs, "Josh-20.html#vs2")
                || isValidVerse(curFile, vs, "2Chr-02.html#vs2")
                || isValidVerse(curFile, vs, "Luke-10.html#vs1")
                || isValidVerse(curFile, vs, "Acts-01.html#vs24");
    }  // isAanwijzen

    private static boolean isAfwijzen(final File curFile, final String vs) {
        return isValidVerse(curFile, vs, "1Kgs-02.html#vs16", 20)
                || isValidVerse(curFile, vs, "2Chr-06.html#vs42")
                || isValidVerse(curFile, vs, "Ps-027.html#vs9")
                || isValidVerse(curFile, vs, "Ps-132.html#vs10");
    }  // isAfwijzen

    private static boolean isTerechtwijzen(final File curFile, final String vs) {
        return isValidVerse(curFile, vs, "Gen-21.html#vs25")
                || isValidVerse(curFile, vs, "Prov-09.html#vs8")
                || isValidVerse(curFile, vs, "Prov-19.html#vs25")
                || isValidVerse(curFile, vs, "Matt-18.html#vs15")
                || isValidVerse(curFile, vs, "Acts-20.html#vs31")
                || isValidVerse(curFile, vs, "Rom-15.html#vs14")
                || isValidVerse(curFile, vs, "1Cor-04.html#vs14")
                || isValidVerse(curFile, vs, "Col-3.html#vs16")
                || isValidVerse(curFile, vs, "1Thess-5.html#vs14")
                || isValidVerse(curFile, vs, "2Thess-3.html#vs15")
                || isValidVerse(curFile, vs, "1Tim-5.html#vs20")
                || isValidVerse(curFile, vs, "Titus-1.html#vs13")
                || isValidVerse(curFile, vs, "Titus-2.html#vs15")
                || isValidVerse(curFile, vs, "Jude-1.html#vs15")
                || isValidVerse(curFile, vs, "Rev-03.html#vs19")
                || isValidVerse(curFile, vs, "Didache-02.html#vs7")
                || isValidVerse(curFile, vs, "Didache-15.html#vs3");
    }  // isTerechtwijzen

    private static boolean isToewijzen(final File curFile, final String vs) {
        return isValidVerse(curFile, vs, "Num-34.html#vs29");
    }  // isToewijzen

    private static boolean isWees(final File curFile, final String vs) {
        return isValidVerse(curFile, vs, "Exod-22.html#vs22", 24)
                || isValidVerse(curFile, vs, "Deut-10.html#vs18")
                || isValidVerse(curFile, vs, "Deut-14.html#vs29")
                || isValidVerse(curFile, vs, "Deut-16.html#vs11", 11, 14)
                || isValidVerse(curFile, vs, "Deut-24.html#vs17", 19, 20, 21)
                || isValidVerse(curFile, vs, "Deut-26.html#vs12", 13)
                || isValidVerse(curFile, vs, "Deut-27.html#vs19")
                || isValidVerse(curFile, vs, "Job-06.html#vs27")
                || isValidVerse(curFile, vs, "Job-22.html#vs9")
                || isValidVerse(curFile, vs, "Job-24.html#vs3")
                || isValidVerse(curFile, vs, "Job-29.html#vs12")
                || isValidVerse(curFile, vs, "Job-31.html#vs17", 21)
                || isValidVerse(curFile, vs, "Ps-010.html#vs14", 18)
                || isValidVerse(curFile, vs, "Ps-068.html#vs6")
                || isValidVerse(curFile, vs, "Ps-082.html#vs3")
                || isValidVerse(curFile, vs, "Ps-094.html#vs6")
                || isValidVerse(curFile, vs, "Ps-109.html#vs9", 12)
                || isValidVerse(curFile, vs, "Ps-146.html#vs9")
                || isValidVerse(curFile, vs, "Prov-23.html#vs10")
                || isValidVerse(curFile, vs, "Isa-01.html#vs17", 23)
                || isValidVerse(curFile, vs, "Isa-09.html#vs16")
                || isValidVerse(curFile, vs, "Isa-10.html#vs2")
                || isValidVerse(curFile, vs, "Jer-05.html#vs28")
                || isValidVerse(curFile, vs, "Jer-07.html#vs6")
                || isValidVerse(curFile, vs, "Jer-22.html#vs3")
                || isValidVerse(curFile, vs, "Jer-49.html#vs11")
                || isValidVerse(curFile, vs, "Lam-5.html#vs3")
                || isValidVerse(curFile, vs, "Ezek-22.html#vs7")
                || isValidVerse(curFile, vs, "Hos-14.html#vs4")
                || isValidVerse(curFile, vs, "Zech-07.html#vs10")
                || isValidVerse(curFile, vs, "Mal-3.html#vs5")
                || isValidVerse(curFile, vs, "John-14.html#vs18")
                || isValidVerse(curFile, vs, "Jas-1.html#vs27");
    }  // isWees

    private static boolean isWezen(final File curFile, final String vs, final String arg) {
        if (arg.equals("wezens")) {
            return true;
        }
        return isValidVerse(curFile, vs, "Gen-02.html#vs7", 19)
                || isValidVerse(curFile, vs, "1Sam-28.html#vs13")
                || isValidVerse(curFile, vs, "Ezek-10.html#vs15", 20)
                || isValidVerse(curFile, vs, "1Cor-15.html#vs45")
                || isValidVerse(curFile, vs, "Rev-16.html#vs3");
    }  // isWezen

    private static boolean isWijs(final File curFile, final String vs) {
        return isValidVerse(curFile, vs, "Gen-41.html#vs33", 39)
                || isValidVerse(curFile, vs, "Exod-28.html#vs3")
                || isValidVerse(curFile, vs, "Exod-35.html#vs25", 26)
                || isValidVerse(curFile, vs, "Deut-01.html#vs13", 15)
                || isValidVerse(curFile, vs, "Deut-04.html#vs6")
                || isValidVerse(curFile, vs, "Deut-32.html#vs29")
                || isValidVerse(curFile, vs, "Judg-05.html#vs29")
                || isValidVerse(curFile, vs, "2Sam-13.html#vs3")
                || isValidVerse(curFile, vs, "2Sam-14.html#vs2", 20)
                || isValidVerse(curFile, vs, "2Sam-20.html#vs16")
                || isValidVerse(curFile, vs, "1Kgs-02.html#vs9")
                || isValidVerse(curFile, vs, "1Kgs-03.html#vs12")
                || isValidVerse(curFile, vs, "1Kgs-05.html#vs7")
                || isValidVerse(curFile, vs, "2Chr-02.html#vs12", 13)
                || isValidVerse(curFile, vs, "Job-09.html#vs4")
                || isValidVerse(curFile, vs, "Job-32.html#vs9")
                || isValidVerse(curFile, vs, "Job-34.html#vs34")
                || isValidVerse(curFile, vs, "Job-37.html#vs12")
                || isValidVerse(curFile, vs, "Ps-090.html#vs12")
                || isValidVerse(curFile, vs, "Ps-107.html#vs43")
                || isValidVerse(curFile, vs, "Prov-01.html#vs5")
                || isValidVerse(curFile, vs, "Prov-03.html#vs7")
                || isValidVerse(curFile, vs, "Prov-06.html#vs6")
                || isValidVerse(curFile, vs, "Prov-08.html#vs33")
                || isValidVerse(curFile, vs, "Prov-09.html#vs12")
                || isValidVerse(curFile, vs, "Prov-10.html#vs1", 8)
                || isValidVerse(curFile, vs, "Prov-11.html#vs14", 29, 30)
                || isValidVerse(curFile, vs, "Prov-12.html#vs5", 15)
                || isValidVerse(curFile, vs, "Prov-13.html#vs1", 20)
                || isValidVerse(curFile, vs, "Prov-14.html#vs1")
                || isValidVerse(curFile, vs, "Prov-16.html#vs14")
                || isValidVerse(curFile, vs, "Prov-17.html#vs28")
                || isValidVerse(curFile, vs, "Prov-19.html#vs20")
                || isValidVerse(curFile, vs, "Prov-20.html#vs1", 26)
                || isValidVerse(curFile, vs, "Prov-21.html#vs11")
                || isValidVerse(curFile, vs, "Prov-23.html#vs15", 19, 24)
                || isValidVerse(curFile, vs, "Prov-24.html#vs5")
                || isValidVerse(curFile, vs, "Prov-25.html#vs12")
                || isValidVerse(curFile, vs, "Prov-26.html#vs5", 5, 12)
                || isValidVerse(curFile, vs, "Prov-27.html#vs11")
                || isValidVerse(curFile, vs, "Prov-28.html#vs11")
                || isValidVerse(curFile, vs, "Prov-29.html#vs9")
                || isValidVerse(curFile, vs, "Prov-30.html#vs24")
                || isValidVerse(curFile, vs, "Eccl-02.html#vs15", 19)
                || isValidVerse(curFile, vs, "Eccl-04.html#vs13")
                || isValidVerse(curFile, vs, "Eccl-07.html#vs16", 23)
                || isValidVerse(curFile, vs, "Eccl-09.html#vs15")
                || isValidVerse(curFile, vs, "Isa-05.html#vs21")
                || isValidVerse(curFile, vs, "Isa-31.html#vs2")
                || isValidVerse(curFile, vs, "Jer-04.html#vs22")
                || isValidVerse(curFile, vs, "Jer-08.html#vs8")
                || isValidVerse(curFile, vs, "Jer-09.html#vs12")
                || isValidVerse(curFile, vs, "Dan-01.html#vs20")
                || isValidVerse(curFile, vs, "Hos-14.html#vs10")
                || isValidVerse(curFile, vs, "Zech-09.html#vs2")
                || isValidVerse(curFile, vs, "Matt-25.html#vs2")
                || isValidVerse(curFile, vs, "Acts-24.html#vs3")
                || isValidVerse(curFile, vs, "Rom-11.html#vs25")
                || isValidVerse(curFile, vs, "Rom-12.html#vs16")
                || isValidVerse(curFile, vs, "Rom-16.html#vs19", 27)
                || isValidVerse(curFile, vs, "1Cor-03.html#vs10", 18)
                || isValidVerse(curFile, vs, "1Cor-04.html#vs10")
                || isValidVerse(curFile, vs, "1Cor-06.html#vs5")
                || isValidVerse(curFile, vs, "2Cor-11.html#vs19")
                || isValidVerse(curFile, vs, "1Tim-1.html#vs17")
                || isValidVerse(curFile, vs, "2Tim-3.html#vs15")
                || isValidVerse(curFile, vs, "Jas-3.html#vs13");
    }  // isWijs

    private static boolean isWijzeManier(final File curFile, final String vs) {
        return isValidVerse(curFile, vs, "Gen-18.html#vs11")
                || isValidVerse(curFile, vs, "Gen-31.html#vs35")
                || isValidVerse(curFile, vs, "Gen-34.html#vs13")
                || isValidVerse(curFile, vs, "Lev-19.html#vs15")
                || isValidVerse(curFile, vs, "Deut-31.html#vs29")
                || isValidVerse(curFile, vs, "Josh-06.html#vs15")
                || isValidVerse(curFile, vs, "Josh-23.html#vs12")
                || isValidVerse(curFile, vs, "Judg-18.html#vs7")
                || isValidVerse(curFile, vs, "1Kgs-18.html#vs28")
                || isValidVerse(curFile, vs, "2Kgs-17.html#vs26", 27)
                || isValidVerse(curFile, vs, "1Chr-22.html#vs15")
                || isValidVerse(curFile, vs, "Ezra-06.html#vs13")
                || isValidVerse(curFile, vs, "Neh-06.html#vs4", 5)
                || isValidVerse(curFile, vs, "Ps-009.html#vs9")
                || isValidVerse(curFile, vs, "Ps-096.html#vs10")
                || isValidVerse(curFile, vs, "Ps-098.html#vs9")
                || isValidVerse(curFile, vs, "Eccl-05.html#vs15")
                || isValidVerse(curFile, vs, "Isa-28.html#vs26")
                || isValidVerse(curFile, vs, "Jer-17.html#vs11")
                || isValidVerse(curFile, vs, "Dan-08.html#vs24")
                || isValidVerse(curFile, vs, "Matt-03.html#vs15")
                || isValidVerse(curFile, vs, "Matt-23.html#vs37")
                || isValidVerse(curFile, vs, "Luke-13.html#vs34")
                || isValidVerse(curFile, vs, "Luke-17.html#vs20")
                || isValidVerse(curFile, vs, "John-05.html#vs19")
                || isValidVerse(curFile, vs, "Acts-01.html#vs11")
                || isValidVerse(curFile, vs, "Acts-07.html#vs28")
                || isValidVerse(curFile, vs, "Acts-15.html#vs11")
                || isValidVerse(curFile, vs, "Acts-22.html#vs3")
                || isValidVerse(curFile, vs, "Acts-25.html#vs11", 16)
                || isValidVerse(curFile, vs, "Rom-03.html#vs5")
                || isValidVerse(curFile, vs, "Rom-06.html#vs19")
                || isValidVerse(curFile, vs, "Rom-13.html#vs13")
                || isValidVerse(curFile, vs, "Rom-16.html#vs2")
                || isValidVerse(curFile, vs, "1Cor-07.html#vs7", 36)
                || isValidVerse(curFile, vs, "1Cor-09.html#vs27")
                || isValidVerse(curFile, vs, "1Cor-11.html#vs27", 29)
                || isValidVerse(curFile, vs, "1Cor-14.html#vs40")
                || isValidVerse(curFile, vs, "2Cor-13.html#vs5")
                || isValidVerse(curFile, vs, "Gal-3.html#vs15")
                || isValidVerse(curFile, vs, "Eph-4.html#vs14")
                || isValidVerse(curFile, vs, "Phil-1.html#vs18")
                || isValidVerse(curFile, vs, "Col-1.html#vs10")
                || isValidVerse(curFile, vs, "Col-4.html#vs1")
                || isValidVerse(curFile, vs, "1Thess-4.html#vs12", 14)
                || isValidVerse(curFile, vs, "2Thess-2.html#vs3")
                || isValidVerse(curFile, vs, "2Thess-3.html#vs16")
                || isValidVerse(curFile, vs, "2Tim-3.html#vs8")
                || isValidVerse(curFile, vs, "Heb-01.html#vs1")
                || isValidVerse(curFile, vs, "Heb-04.html#vs15")
                || isValidVerse(curFile, vs, "Heb-12.html#vs28")
                || isValidVerse(curFile, vs, "Jude-1.html#vs7", 8, 15);
    }  // isWijzeManier

    private static boolean isWijzePersoon(final File curFile, final String vs) {
        return isValidVerse(curFile, vs, "Gen-41.html#vs8")
                || isValidVerse(curFile, vs, "Exod-07.html#vs11")
                || isValidVerse(curFile, vs, "Deut-16.html#vs19")
                || isValidVerse(curFile, vs, "2Chr-02.html#vs7", 14)
                || isValidVerse(curFile, vs, "Esth-01.html#vs13")
                || isValidVerse(curFile, vs, "Esth-06.html#vs13")
                || isValidVerse(curFile, vs, "Job-05.html#vs13")
                || isValidVerse(curFile, vs, "Job-15.html#vs2", 18)
                || isValidVerse(curFile, vs, "Job-17.html#vs10")
                || isValidVerse(curFile, vs, "Job-34.html#vs2")
                || isValidVerse(curFile, vs, "Ps-049.html#vs11")
                || isValidVerse(curFile, vs, "Prov-01.html#vs6")
                || isValidVerse(curFile, vs, "Prov-03.html#vs35")
                || isValidVerse(curFile, vs, "Prov-09.html#vs8", 9)
                || isValidVerse(curFile, vs, "Prov-10.html#vs14")
                || isValidVerse(curFile, vs, "Prov-12.html#vs18")
                || isValidVerse(curFile, vs, "Prov-13.html#vs14", 20)
                || isValidVerse(curFile, vs, "Prov-14.html#vs3", 16, 24)
                || isValidVerse(curFile, vs, "Prov-15.html#vs2", 7, 12, 20, 31)
                || isValidVerse(curFile, vs, "Prov-16.html#vs21", 23)
                || isValidVerse(curFile, vs, "Prov-18.html#vs15")
                || isValidVerse(curFile, vs, "Prov-21.html#vs11", 20, 22)
                || isValidVerse(curFile, vs, "Prov-22.html#vs17")
                || isValidVerse(curFile, vs, "Prov-24.html#vs23")
                || isValidVerse(curFile, vs, "Prov-29.html#vs8", 11)
                || isValidVerse(curFile, vs, "Eccl-02.html#vs14", 16)
                || isValidVerse(curFile, vs, "Eccl-06.html#vs8")
                || isValidVerse(curFile, vs, "Eccl-07.html#vs4", 5, 7, 19)
                || isValidVerse(curFile, vs, "Eccl-08.html#vs1", 5, 17)
                || isValidVerse(curFile, vs, "Eccl-09.html#vs1", 11, 17)
                || isValidVerse(curFile, vs, "Eccl-10.html#vs2", 12)
                || isValidVerse(curFile, vs, "Eccl-12.html#vs9", 11)
                || isValidVerse(curFile, vs, "Isa-19.html#vs11")
                || isValidVerse(curFile, vs, "Isa-29.html#vs14")
                || isValidVerse(curFile, vs, "Isa-44.html#vs25")
                || isValidVerse(curFile, vs, "Jer-08.html#vs9")
                || isValidVerse(curFile, vs, "Jer-09.html#vs23")
                || isValidVerse(curFile, vs, "Jer-10.html#vs7")
                || isValidVerse(curFile, vs, "Jer-18.html#vs18")
                || isValidVerse(curFile, vs, "Jer-50.html#vs35")
                || isValidVerse(curFile, vs, "Jer-51.html#vs57")
                || isValidVerse(curFile, vs, "Ezek-27.html#vs8", 9)
                || isValidVerse(curFile, vs, "Dan-02.html#vs12", 13, 14, 18, 21, 24, 27, 48)
                || isValidVerse(curFile, vs, "Dan-04.html#vs6", 18)
                || isValidVerse(curFile, vs, "Dan-05.html#vs7", 8, 15)
                || isValidVerse(curFile, vs, "Obad-1.html#vs8")
                || isValidVerse(curFile, vs, "Matt-02.html#vs1", 7, 16)
                || isValidVerse(curFile, vs, "Matt-11.html#vs25")
                || isValidVerse(curFile, vs, "Matt-23.html#vs34")
                || isValidVerse(curFile, vs, "Matt-25.html#vs4", 8, 9)
                || isValidVerse(curFile, vs, "Luke-10.html#vs21")
                || isValidVerse(curFile, vs, "Rom-01.html#vs14", 22)
                || isValidVerse(curFile, vs, "1Cor-01.html#vs19", 20, 26, 27)
                || isValidVerse(curFile, vs, "1Cor-03.html#vs19", 20)
                || isValidVerse(curFile, vs, "Eph-5.html#vs15");
    }  // isWijzePersoon

    private static boolean isZijn(final File curFile, final String vs) {
        return isValidVerse(curFile, vs, "Gen-01.html#vs22", 28)
                || isValidVerse(curFile, vs, "Gen-09.html#vs1", 7)
                || isValidVerse(curFile, vs, "Gen-15.html#vs1")
                || isValidVerse(curFile, vs, "Gen-17.html#vs1")
                || isValidVerse(curFile, vs, "Gen-21.html#vs17")
                || isValidVerse(curFile, vs, "Gen-24.html#vs6")
                || isValidVerse(curFile, vs, "Gen-26.html#vs24")
                || isValidVerse(curFile, vs, "Gen-27.html#vs29")
                || isValidVerse(curFile, vs, "Gen-31.html#vs24", 29)
                || isValidVerse(curFile, vs, "Gen-35.html#vs11")
                || isValidVerse(curFile, vs, "Gen-43.html#vs23")
                || isValidVerse(curFile, vs, "Gen-45.html#vs5")
                || isValidVerse(curFile, vs, "Gen-46.html#vs3")
                || isValidVerse(curFile, vs, "Gen-50.html#vs19", 21)
                || isValidVerse(curFile, vs, "Exod-10.html#vs28")
                || isValidVerse(curFile, vs, "Exod-14.html#vs13")
                || isValidVerse(curFile, vs, "Exod-19.html#vs12", 15)
                || isValidVerse(curFile, vs, "Exod-20.html#vs20")
                || isValidVerse(curFile, vs, "Exod-23.html#vs21")
                || isValidVerse(curFile, vs, "Exod-34.html#vs2", 12)
                || isValidVerse(curFile, vs, "Lev-20.html#vs7")
                || isValidVerse(curFile, vs, "Num-05.html#vs19")
                || isValidVerse(curFile, vs, "Num-14.html#vs9")
                || isValidVerse(curFile, vs, "Num-21.html#vs34")
                || isValidVerse(curFile, vs, "Deut-01.html#vs21", 29)
                || isValidVerse(curFile, vs, "Deut-03.html#vs2", 22)
                || isValidVerse(curFile, vs, "Deut-04.html#vs9", 23)
                || isValidVerse(curFile, vs, "Deut-06.html#vs12")
                || isValidVerse(curFile, vs, "Deut-07.html#vs18")
                || isValidVerse(curFile, vs, "Deut-08.html#vs11")
                || isValidVerse(curFile, vs, "Deut-10.html#vs16")
                || isValidVerse(curFile, vs, "Deut-11.html#vs16")
                || isValidVerse(curFile, vs, "Deut-12.html#vs13", 19, 30)
                || isValidVerse(curFile, vs, "Deut-15.html#vs9")
                || isValidVerse(curFile, vs, "Deut-18.html#vs22")
                || isValidVerse(curFile, vs, "Deut-20.html#vs1", 3)
                || isValidVerse(curFile, vs, "Deut-24.html#vs8")
                || isValidVerse(curFile, vs, "Deut-31.html#vs6", 7, 8, 23)
                || isValidVerse(curFile, vs, "Deut-33.html#vs7", 11, 23)
                || isValidVerse(curFile, vs, "Josh-01.html#vs6", 7, 9, 18)
                || isValidVerse(curFile, vs, "Josh-08.html#vs1")
                || isValidVerse(curFile, vs, "Josh-10.html#vs8", 25)
                || isValidVerse(curFile, vs, "Josh-11.html#vs6")
                || isValidVerse(curFile, vs, "Josh-23.html#vs6", 11)
                || isValidVerse(curFile, vs, "Judg-04.html#vs18")
                || isValidVerse(curFile, vs, "Judg-06.html#vs23")
                || isValidVerse(curFile, vs, "Judg-09.html#vs8", 10, 12)
                || isValidVerse(curFile, vs, "Judg-11.html#vs6")
                || isValidVerse(curFile, vs, "Judg-13.html#vs4")
                || isValidVerse(curFile, vs, "Judg-17.html#vs10")
                || isValidVerse(curFile, vs, "Judg-18.html#vs19")
                || isValidVerse(curFile, vs, "Judg-21.html#vs22")
                || isValidVerse(curFile, vs, "Ruth-3.html#vs11")
                || isValidVerse(curFile, vs, "1Sam-04.html#vs90, 20")
                || isValidVerse(curFile, vs, "1Sam-12.html#vs20")
                || isValidVerse(curFile, vs, "1Sam-15.html#vs13")
                || isValidVerse(curFile, vs, "1Sam-18.html#vs17")
                || isValidVerse(curFile, vs, "1Sam-19.html#vs2")
                || isValidVerse(curFile, vs, "1Sam-22.html#vs23")
                || isValidVerse(curFile, vs, "1Sam-23.html#vs17")
                || isValidVerse(curFile, vs, "1Sam-28.html#vs13")
                || isValidVerse(curFile, vs, "2Sam-02.html#vs5", 7)
                || isValidVerse(curFile, vs, "2Sam-09.html#vs7")
                || isValidVerse(curFile, vs, "2Sam-10.html#vs12")
                || isValidVerse(curFile, vs, "2Sam-13.html#vs28")
                || isValidVerse(curFile, vs, "2Sam-14.html#vs2")
                || isValidVerse(curFile, vs, "1Kgs-02.html#vs2")
                || isValidVerse(curFile, vs, "1Kgs-17.html#vs13")
                || isValidVerse(curFile, vs, "2Kgs-01.html#vs15")
                || isValidVerse(curFile, vs, "2Kgs-06.html#vs9", 16)
                || isValidVerse(curFile, vs, "2Kgs-19.html#vs6")
                || isValidVerse(curFile, vs, "2Kgs-25.html#vs24")
                || isValidVerse(curFile, vs, "1Chr-19.html#vs13")
                || isValidVerse(curFile, vs, "1Chr-22.html#vs13")
                || isValidVerse(curFile, vs, "1Chr-28.html#vs10", 20)
                || isValidVerse(curFile, vs, "2Chr-15.html#vs7")
                || isValidVerse(curFile, vs, "2Chr-19.html#vs11")
                || isValidVerse(curFile, vs, "2Chr-20.html#vs15", 17)
                || isValidVerse(curFile, vs, "2Chr-25.html#vs8")
                || isValidVerse(curFile, vs, "2Chr-29.html#vs11")
                || isValidVerse(curFile, vs, "2Chr-30.html#vs7", 8)
                || isValidVerse(curFile, vs, "2Chr-32.html#vs7")
                || isValidVerse(curFile, vs, "Ezra-10.html#vs4")
                || isValidVerse(curFile, vs, "Neh-04.html#vs14")
                || isValidVerse(curFile, vs, "Neh-08.html#vs11", 12)
                || isValidVerse(curFile, vs, "Job-06.html#vs28")
                || isValidVerse(curFile, vs, "Job-19.html#vs29")
                || isValidVerse(curFile, vs, "Job-21.html#vs5")
                || isValidVerse(curFile, vs, "Job-37.html#vs6")
                || isValidVerse(curFile, vs, "Ps-004.html#vs2", 5)
                || isValidVerse(curFile, vs, "Ps-006.html#vs3")
                || isValidVerse(curFile, vs, "Ps-009.html#vs14")
                || isValidVerse(curFile, vs, "Ps-022.html#vs24")
                || isValidVerse(curFile, vs, "Ps-025.html#vs16")
                || isValidVerse(curFile, vs, "Ps-026.html#vs11")
                || isValidVerse(curFile, vs, "Ps-027.html#vs7", 14)
                || isValidVerse(curFile, vs, "Ps-030.html#vs11")
                || isValidVerse(curFile, vs, "Ps-031.html#vs3", 10, 25)
                || isValidVerse(curFile, vs, "Ps-032.html#vs9")
                || isValidVerse(curFile, vs, "Ps-037.html#vs10")
                || isValidVerse(curFile, vs, "Ps-041.html#vs5", 11)
                || isValidVerse(curFile, vs, "Ps-049.html#vs17")
                || isValidVerse(curFile, vs, "Ps-051.html#vs3")
                || isValidVerse(curFile, vs, "Ps-056.html#vs2")
                || isValidVerse(curFile, vs, "Ps-057.html#vs2")
                || isValidVerse(curFile, vs, "Ps-059.html#vs6")
                || isValidVerse(curFile, vs, "Ps-071.html#vs3")
                || isValidVerse(curFile, vs, "Ps-083.html#vs2")
                || isValidVerse(curFile, vs, "Ps-086.html#vs3", 16)
                || isValidVerse(curFile, vs, "Ps-119.html#vs17", 58, 122, 132)
                || isValidVerse(curFile, vs, "Ps-123.html#vs3")
                || isValidVerse(curFile, vs, "Ps-141.html#vs5")
                || isValidVerse(curFile, vs, "Prov-03.html#vs7", 25, 31)
                || isValidVerse(curFile, vs, "Prov-22.html#vs26")
                || isValidVerse(curFile, vs, "Prov-23.html#vs3", 6)
                || isValidVerse(curFile, vs, "Prov-24.html#vs1", 19, 28)
                || isValidVerse(curFile, vs, "Prov-27.html#vs11")
                || isValidVerse(curFile, vs, "Eccl-05.html#vs1", 7)
                || isValidVerse(curFile, vs, "Eccl-07.html#vs9", 16, 17)
                || isValidVerse(curFile, vs, "Eccl-12.html#vs12")
                || isValidVerse(curFile, vs, "Song-2.html#vs17")
                || isValidVerse(curFile, vs, "Song-8.html#vs14")
                || isValidVerse(curFile, vs, "Isa-03.html#vs6")
                || isValidVerse(curFile, vs, "Isa-07.html#vs4")
                || isValidVerse(curFile, vs, "Isa-10.html#vs24")
                || isValidVerse(curFile, vs, "Isa-16.html#vs4")
                || isValidVerse(curFile, vs, "Isa-33.html#vs2")
                || isValidVerse(curFile, vs, "Isa-35.html#vs4")
                || isValidVerse(curFile, vs, "Isa-37.html#vs6")
                || isValidVerse(curFile, vs, "Isa-38.html#vs14")
                || isValidVerse(curFile, vs, "Isa-40.html#vs9")
                || isValidVerse(curFile, vs, "Isa-41.html#vs6", 10, 13, 14)
                || isValidVerse(curFile, vs, "Isa-43.html#vs1", 5)
                || isValidVerse(curFile, vs, "Isa-44.html#vs2", 8)
                || isValidVerse(curFile, vs, "Isa-46.html#vs8")
                || isValidVerse(curFile, vs, "Isa-51.html#vs7")
                || isValidVerse(curFile, vs, "Isa-54.html#vs2", 4)
                || isValidVerse(curFile, vs, "Isa-64.html#vs9")
                || isValidVerse(curFile, vs, "Isa-65.html#vs18")
                || isValidVerse(curFile, vs, "Isa-66.html#vs10")
                || isValidVerse(curFile, vs, "Jer-01.html#vs8", 17)
                || isValidVerse(curFile, vs, "Jer-02.html#vs12")
                || isValidVerse(curFile, vs, "Jer-10.html#vs5")
                || isValidVerse(curFile, vs, "Jer-17.html#vs17")
                || isValidVerse(curFile, vs, "Jer-30.html#vs10")
                || isValidVerse(curFile, vs, "Jer-40.html#vs9")
                || isValidVerse(curFile, vs, "Jer-42.html#vs11")
                || isValidVerse(curFile, vs, "Jer-46.html#vs27", 28)
                || isValidVerse(curFile, vs, "Jer-47.html#vs6")
                || isValidVerse(curFile, vs, "Jer-50.html#vs8")
                || isValidVerse(curFile, vs, "Lam-3.html#vs57")
                || isValidVerse(curFile, vs, "Lam-4.html#vs21")
                || isValidVerse(curFile, vs, "Ezek-02.html#vs6", 8)
                || isValidVerse(curFile, vs, "Ezek-03.html#vs9")
                || isValidVerse(curFile, vs, "Ezek-21.html#vs16")
                || isValidVerse(curFile, vs, "Ezek-38.html#vs7")
                || isValidVerse(curFile, vs, "Dan-10.html#vs12", 19)
                || isValidVerse(curFile, vs, "Hos-09.html#vs1")
                || isValidVerse(curFile, vs, "Joel-2.html#vs21")
                || isValidVerse(curFile, vs, "Hab-2.html#vs20")
                || isValidVerse(curFile, vs, "Zeph-1.html#vs7")
                || isValidVerse(curFile, vs, "Zeph-3.html#vs14", 16)
                || isValidVerse(curFile, vs, "Hag-2.html#vs5", 6)
                || isValidVerse(curFile, vs, "Zech-01.html#vs4")
                || isValidVerse(curFile, vs, "Zech-02.html#vs13")
                || isValidVerse(curFile, vs, "Zech-08.html#vs13", 15)
                || isValidVerse(curFile, vs, "Mal-2.html#vs15", 16)
                || isValidVerse(curFile, vs, "Matt-01.html#vs20")
                || isValidVerse(curFile, vs, "Matt-06.html#vs1", 25, 31, 34)
                || isValidVerse(curFile, vs, "Matt-07.html#vs15")
                || isValidVerse(curFile, vs, "Matt-10.html#vs16", 17, 26, 28, 31)
                || isValidVerse(curFile, vs, "Matt-14.html#vs27")
                || isValidVerse(curFile, vs, "Matt-16.html#vs6")
                || isValidVerse(curFile, vs, "Matt-17.html#vs7")
                || isValidVerse(curFile, vs, "Matt-24.html#vs42")
                || isValidVerse(curFile, vs, "Matt-25.html#vs13")
                || isValidVerse(curFile, vs, "Matt-28.html#vs9", 10)
                || isValidVerse(curFile, vs, "Mark-04.html#vs39")
                || isValidVerse(curFile, vs, "Mark-05.html#vs34", 36)
                || isValidVerse(curFile, vs, "Mark-06.html#vs50")
                || isValidVerse(curFile, vs, "Mark-09.html#vs22")
                || isValidVerse(curFile, vs, "Mark-13.html#vs11", 35, 37)
                || isValidVerse(curFile, vs, "Mark-16.html#vs6")
                || isValidVerse(curFile, vs, "Luke-01.html#vs13", 28, 30)
                || isValidVerse(curFile, vs, "Luke-02.html#vs10")
                || isValidVerse(curFile, vs, "Luke-03.html#vs14")
                || isValidVerse(curFile, vs, "Luke-05.html#vs10")
                || isValidVerse(curFile, vs, "Luke-06.html#vs36")
                || isValidVerse(curFile, vs, "Luke-08.html#vs50")
                || isValidVerse(curFile, vs, "Luke-10.html#vs1")
                || isValidVerse(curFile, vs, "Luke-12.html#vs1", 4, 5, 7, 11, 15, 19, 22, 29, 32, 36, 40)
                || isValidVerse(curFile, vs, "Luke-15.html#vs6", 9)
                || isValidVerse(curFile, vs, "Luke-17.html#vs3")
                || isValidVerse(curFile, vs, "Luke-18.html#vs13")
                || isValidVerse(curFile, vs, "Luke-19.html#vs17", 19)
                || isValidVerse(curFile, vs, "Luke-20.html#vs46")
                || isValidVerse(curFile, vs, "Luke-21.html#vs9", 34)
                || isValidVerse(curFile, vs, "John-06.html#vs20")
                || isValidVerse(curFile, vs, "John-12.html#vs15")
                || isValidVerse(curFile, vs, "John-20.html#vs27")
                || isValidVerse(curFile, vs, "Acts-05.html#vs35")
                || isValidVerse(curFile, vs, "Acts-18.html#vs9")
                || isValidVerse(curFile, vs, "Acts-20.html#vs31")
                || isValidVerse(curFile, vs, "Acts-27.html#vs24")
                || isValidVerse(curFile, vs, "Rom-12.html#vs11", 12, 13, 16, 17)
                || isValidVerse(curFile, vs, "Rom-13.html#vs8")
                || isValidVerse(curFile, vs, "Rom-15.html#vs10")
                || isValidVerse(curFile, vs, "1Cor-11.html#vs1")
                || isValidVerse(curFile, vs, "1Cor-14.html#vs20")
                || isValidVerse(curFile, vs, "1Cor-15.html#vs58")
                || isValidVerse(curFile, vs, "1Cor-16.html#vs13")
                || isValidVerse(curFile, vs, "2Cor-08.html#vs7")
                || isValidVerse(curFile, vs, "2Cor-13.html#vs11")
                || isValidVerse(curFile, vs, "Gal-4.html#vs12", 27)
                || isValidVerse(curFile, vs, "Eph-4.html#vs32")
                || isValidVerse(curFile, vs, "Eph-5.html#vs1", 7, 17, 21, 22)
                || isValidVerse(curFile, vs, "Eph-6.html#vs1", 5)
                || isValidVerse(curFile, vs, "Phil-3.html#vs17")
                || isValidVerse(curFile, vs, "Phil-4.html#vs6")
                || isValidVerse(curFile, vs, "Col-2.html#vs7")
                || isValidVerse(curFile, vs, "Col-3.html#vs15", 18, 19, 20, 22)
                || isValidVerse(curFile, vs, "Col-4.html#vs2")
                || isValidVerse(curFile, vs, "1Tim-4.html#vs12")
                || isValidVerse(curFile, vs, "2Tim-4.html#vs5", 15)
                || isValidVerse(curFile, vs, "Heb-10.html#vs1")
                || isValidVerse(curFile, vs, "Heb-13.html#vs5", 17)
                || isValidVerse(curFile, vs, "Jas-1.html#vs1", 22)
                || isValidVerse(curFile, vs, "Jas-5.html#vs7")
                || isValidVerse(curFile, vs, "1Pet-1.html#vs1, 16")
                || isValidVerse(curFile, vs, "1Pet-2.html#vs18")
                || isValidVerse(curFile, vs, "1Pet-3.html#vs1", 8, 14, 15)
                || isValidVerse(curFile, vs, "1Pet-4.html#vs7", 9)
                || isValidVerse(curFile, vs, "1Pet-5.html#vs5", 8)
                || isValidVerse(curFile, vs, "2Pet-3.html#vs17")
                || isValidVerse(curFile, vs, "1John-5.html#vs21")
                || isValidVerse(curFile, vs, "Rev-01.html#vs17")
                || isValidVerse(curFile, vs, "Rev-02.html#vs10")
                || isValidVerse(curFile, vs, "Rev-03.html#vs2", 19)
                || isValidVerse(curFile, vs, "Didache-03.html#vs2", 3, 5, 6, 7, 8)
                || isValidVerse(curFile, vs, "Didache-04.html#vs3", 5)
                || isValidVerse(curFile, vs, "Didache-16.html#vs1");
    }  // isZijn

    private static boolean isWijzen(final File curFile, final String vs, final String arg) {
        return !isAanwijzen(curFile, vs)
                && !isAfwijzen(curFile, vs)
                && !isTerechtwijzen(curFile, vs)
                && !isToewijzen(curFile, vs)
                && !isWees(curFile, vs)
                && !isWezen(curFile, vs, arg)
                && !isWijs(curFile, vs)
                && !isWijzeManier(curFile, vs)
                && !isWijzePersoon(curFile, vs)
                && !isZijn(curFile, vs);
    }  // isWijzen

}
