package rb.hsv.appendix.ccd.valid;

import org.jetbrains.annotations.NotNull;

import java.io.File;

import static rb.hsv.appendix.ccd.valid.util.ValidUtil.isValidVerse;

public class ValidKeren {

    public static boolean isValid(final @NotNull String keyArg, final File curFile, final String vs) {
        return switch (keyArg) {
            case "afkeer" -> isAfkeer(curFile, vs);
            case "afkeren" -> isAfkeren(curFile, vs);
            case "keer" -> isKeer(curFile, vs);
            case "omkeer" -> isOmkeer(curFile, vs);
            case "omkeren" -> isOmkeren(curFile, vs);
            case "ondersteboven keren" -> isOnderstebovenKeren(curFile, vs);
            case "tegen [iets] keren" -> isTegenIetsKeren(curFile, vs);
            case "terugkeer" -> isTerugkeer(curFile, vs);
            case "terugkeren" -> isTerugkeren(curFile, vs);
            case "toekeren" -> isToekeren(curFile, vs);
            case "uitkeren" -> isUitkeren(curFile, vs);
            case "keren" -> isKeren(curFile, vs);
            default -> true;
        };
    }

    public static boolean isAfkeer(final File curFile, final String vs) {
        return isValidVerse(curFile, vs, "Gen-27.html#vs46")
                || isValidVerse(curFile, vs, "Exod-18.html#vs21")
                || isValidVerse(curFile, vs, "Lev-20.html#vs23")
                || isValidVerse(curFile, vs, "Num-21.html#vs5")
                || isValidVerse(curFile, vs, "Deut-22.html#vs13", 16)
                || isValidVerse(curFile, vs, "Deut-24.html#vs3")
                || isValidVerse(curFile, vs, "1Kgs-11.html#vs25")
                || isValidVerse(curFile, vs, "Prov-03.html#vs11")
                || isValidVerse(curFile, vs, "Jer-08.html#vs5")
                || isValidVerse(curFile, vs, "Hos-11.html#vs7")
                || isValidVerse(curFile, vs, "Zech-11.html#vs8")
                || isValidVerse(curFile, vs, "Rom-12.html#vs9");
    } // isAfkeer

    public static boolean isAfkeren(final File curFile, final String vs) {
        return isValidVerse(curFile, vs, "Josh-22.html#vs16", 18, 23)
                || isValidVerse(curFile, vs, "2Kgs-18.html#vs14")
                || isValidVerse(curFile, vs, "2Kgs-23.html#vs26")
                || isValidVerse(curFile, vs, "2Chr-12.html#vs12")
                || isValidVerse(curFile, vs, "2Chr-35.html#vs22")
                || isValidVerse(curFile, vs, "Job-01.html#vs1", 8)
                || isValidVerse(curFile, vs, "Job-02.html#vs3")
                || isValidVerse(curFile, vs, "Job-09.html#vs13")
                || isValidVerse(curFile, vs, "Ps-034.html#vs15")
                || isValidVerse(curFile, vs, "Ps-037.html#vs27")
                || isValidVerse(curFile, vs, "Prov-03.html#vs7")
                || isValidVerse(curFile, vs, "Prov-04.html#vs27")
                || isValidVerse(curFile, vs, "Prov-13.html#vs19")
                || isValidVerse(curFile, vs, "Prov-14.html#vs16")
                || isValidVerse(curFile, vs, "Prov-15.html#vs1")
                || isValidVerse(curFile, vs, "Prov-16.html#vs6", 17)
                || isValidVerse(curFile, vs, "Isa-05.html#vs25")
                || isValidVerse(curFile, vs, "Isa-09.html#vs11", 16, 20)
                || isValidVerse(curFile, vs, "Isa-10.html#vs4")
                || isValidVerse(curFile, vs, "Isa-30.html#vs11")
                || isValidVerse(curFile, vs, "Jer-04.html#vs8")
                || isValidVerse(curFile, vs, "Jer-08.html#vs6")
                || isValidVerse(curFile, vs, "Ezek-14.html#vs6")
                || isValidVerse(curFile, vs, "Ezek-18.html#vs8")
                || isValidVerse(curFile, vs, "Dan-09.html#vs13")
                || isValidVerse(curFile, vs, "Matt-05.html#vs42")
                || isValidVerse(curFile, vs, "Acts-07.html#vs42")
                || isValidVerse(curFile, vs, "Rom-16.html#vs17")
                || isValidVerse(curFile, vs, "2Tim-3.html#vs5")
                || isValidVerse(curFile, vs, "Didache-04.html#vs8");
    } // isAfkeren

    public static boolean isKeer(final File curFile, final String vs) {
        return isValidVerse(curFile, vs, "Gen-22.html#vs15")
                || isValidVerse(curFile, vs, "Gen-27.html#vs36")
                || isValidVerse(curFile, vs, "Gen-31.html#vs7", 41)
                || isValidVerse(curFile, vs, "Gen-33.html#vs3")
                || isValidVerse(curFile, vs, "Gen-35.html#vs17")
                || isValidVerse(curFile, vs, "Gen-41.html#vs32")
                || isValidVerse(curFile, vs, "Gen-43.html#vs18", 20, 34)
                || isValidVerse(curFile, vs, "Exod-08.html#vs32")
                || isValidVerse(curFile, vs, "Exod-09.html#vs14", 27)
                || isValidVerse(curFile, vs, "Exod-10.html#vs17")
                || isValidVerse(curFile, vs, "Exod-23.html#vs17")
                || isValidVerse(curFile, vs, "Exod-34.html#vs23", 24)
                || isValidVerse(curFile, vs, "Lev-04.html#vs6", 17)
                || isValidVerse(curFile, vs, "Lev-08.html#vs11")
                || isValidVerse(curFile, vs, "Lev-14.html#vs16", 51)
                || isValidVerse(curFile, vs, "Lev-16.html#vs14", 19)
                || isValidVerse(curFile, vs, "Lev-25.html#vs8")
                || isValidVerse(curFile, vs, "Lev-26.html#vs18", 21, 24, 28)
                || isValidVerse(curFile, vs, "Num-10.html#vs6")
                || isValidVerse(curFile, vs, "Num-14.html#vs22")
                || isValidVerse(curFile, vs, "Num-19.html#vs4")
                || isValidVerse(curFile, vs, "Num-20.html#vs11")
                || isValidVerse(curFile, vs, "Num-24.html#vs1", 10)
                || isValidVerse(curFile, vs, "Deut-09.html#vs18", 19)
                || isValidVerse(curFile, vs, "Deut-10.html#vs10")
                || isValidVerse(curFile, vs, "Deut-16.html#vs16")
                || isValidVerse(curFile, vs, "Josh-05.html#vs2")
                || isValidVerse(curFile, vs, "Josh-06.html#vs3", 4)
                || isValidVerse(curFile, vs, "Josh-08.html#vs5", 6)
                || isValidVerse(curFile, vs, "Josh-10.html#vs42")
                || isValidVerse(curFile, vs, "Judg-06.html#vs39")
                || isValidVerse(curFile, vs, "Judg-15.html#vs3")
                || isValidVerse(curFile, vs, "Judg-16.html#vs15",20, 28)
                || isValidVerse(curFile, vs, "Judg-20.html#vs30", 31)
                || isValidVerse(curFile, vs, "1Sam-03.html#vs8", 10)
                || isValidVerse(curFile, vs, "1Sam-17.html#vs30")
                || isValidVerse(curFile, vs, "1Sam-20.html#vs25")
                || isValidVerse(curFile, vs, "1Sam-26.html#vs8")
                || isValidVerse(curFile, vs, "2Sam-14.html#vs29")
                || isValidVerse(curFile, vs, "2Sam-20.html#vs10")
                || isValidVerse(curFile, vs, "1Kgs-22.html#vs16")
                || isValidVerse(curFile, vs, "2Kgs-10.html#vs6")
                || isValidVerse(curFile, vs, "1Chr-15.html#vs13")
                || isValidVerse(curFile, vs, "1Chr-29.html#vs22")
                || isValidVerse(curFile, vs, "2Chr-08.html#vs13")
                || isValidVerse(curFile, vs, "2Chr-18.html#vs15")
                || isValidVerse(curFile, vs, "Neh-06.html#vs4", 5)
                || isValidVerse(curFile, vs, "Neh-13.html#vs20")
                || isValidVerse(curFile, vs, "Esth-09.html#vs29")
                || isValidVerse(curFile, vs, "Job-09.html#vs3")
                || isValidVerse(curFile, vs, "Job-19.html#vs3")
                || isValidVerse(curFile, vs, "Job-33.html#vs14", 29)
                || isValidVerse(curFile, vs, "Job-39.html#vs38")
                || isValidVerse(curFile, vs, "Ps-106.html#vs43")
                || isValidVerse(curFile, vs, "Eccl-07.html#vs22")
                || isValidVerse(curFile, vs, "Isa-11.html#vs11")
                || isValidVerse(curFile, vs, "Isa-66.html#vs8")
                || isValidVerse(curFile, vs, "Jer-01.html#vs13")
                || isValidVerse(curFile, vs, "Jer-10.html#vs18")
                || isValidVerse(curFile, vs, "Jer-13.html#vs3")
                || isValidVerse(curFile, vs, "Jer-16.html#vs21")
                || isValidVerse(curFile, vs, "Jer-33.html#vs1")
                || isValidVerse(curFile, vs, "Ezek-41.html#vs6")
                || isValidVerse(curFile, vs, "Dan-02.html#vs7")
                || isValidVerse(curFile, vs, "Dan-11.html#vs29")
                || isValidVerse(curFile, vs, "Jonah-3.html#vs1")
                || isValidVerse(curFile, vs, "Nah-1.html#vs9")
                || isValidVerse(curFile, vs, "Hag-2.html#vs21")
                || isValidVerse(curFile, vs, "Zech-04.html#vs12")
                || isValidVerse(curFile, vs, "Matt-18.html#vs21")
                || isValidVerse(curFile, vs, "Matt-26.html#vs42", 44)
                || isValidVerse(curFile, vs, "Mark-14.html#vs30", 41, 72)
                || isValidVerse(curFile, vs, "Luke-23.html#vs22")
                || isValidVerse(curFile, vs, "John-03.html#vs4")
                || isValidVerse(curFile, vs, "John-09.html#vs24")
                || isValidVerse(curFile, vs, "John-21.html#vs14", 16, 17)
                || isValidVerse(curFile, vs, "Acts-07.html#vs12", 13)
                || isValidVerse(curFile, vs, "Acts-10.html#vs15")
                || isValidVerse(curFile, vs, "Acts-11.html#vs9")
                || isValidVerse(curFile, vs, "2Cor-12.html#vs14")
                || isValidVerse(curFile, vs, "2Cor-13.html#vs1", 2)
                || isValidVerse(curFile, vs, "Gal-4.html#vs13")
                || isValidVerse(curFile, vs, "Heb-09.html#vs28")
                || isValidVerse(curFile, vs, "Rev-19.html#vs3");
    } // isKeer

    public static boolean isOmkeer(final File curFile, final String vs) {
        return isValidVerse(curFile, vs, "Deut-30.html#vs3")
                || isValidVerse(curFile, vs, "Job-42.html#vs10")
                || isValidVerse(curFile, vs, "Ps-085.html#vs2")
                || isValidVerse(curFile, vs, "Ps-126.html#vs4")
                || isValidVerse(curFile, vs, "Jer-29.html#vs14")
                || isValidVerse(curFile, vs, "Jer-30.html#vs3", 18)
                || isValidVerse(curFile, vs, "Jer-31.html#vs23")
                || isValidVerse(curFile, vs, "Jer-32.html#vs44")
                || isValidVerse(curFile, vs, "Jer-33.html#vs7", 2, 26)
                || isValidVerse(curFile, vs, "Jer-48.html#vs47")
                || isValidVerse(curFile, vs, "Jer-49.html#vs6", 39)
                || isValidVerse(curFile, vs, "Ezek-16.html#vs53")
                || isValidVerse(curFile, vs, "Ezek-29.html#vs14")
                || isValidVerse(curFile, vs, "Ezek-39.html#vs25")
                || isValidVerse(curFile, vs, "Hos-06.html#vs11")
                || isValidVerse(curFile, vs, "Joel-3.html#vs1")
                || isValidVerse(curFile, vs, "Amos-9.html#vs14")
                || isValidVerse(curFile, vs, "Zeph-2.html#vs7")
                || isValidVerse(curFile, vs, "Zeph-3.html#vs20")
                || isValidVerse(curFile, vs, "Jas-1.html#vs17");
    } // isOmkeer

    public static boolean isOmkeren(final File curFile, final String vs) {
        return isValidVerse(curFile, vs, "Gen-18.html#vs22")
                || isValidVerse(curFile, vs, "Exod-07.html#vs23")
                || isValidVerse(curFile, vs, "Exod-10.html#vs6")
                || isValidVerse(curFile, vs, "Exod-32.html#vs15")
                || isValidVerse(curFile, vs, "Num-12.html#vs10")
                || isValidVerse(curFile, vs, "Num-14.html#vs25")
                || isValidVerse(curFile, vs, "Num-21.html#vs33")
                || isValidVerse(curFile, vs, "Deut-01.html#vs7", 24, 40)
                || isValidVerse(curFile, vs, "Deut-02.html#vs1", 3, 8)
                || isValidVerse(curFile, vs, "Deut-03.html#vs1")
                || isValidVerse(curFile, vs, "Deut-09.html#vs15")
                || isValidVerse(curFile, vs, "Deut-10.html#vs5")
                || isValidVerse(curFile, vs, "Josh-08.html#vs21")
                || isValidVerse(curFile, vs, "Judg-18.html#vs21", 26)
                || isValidVerse(curFile, vs, "Judg-20.html#vs39", 41, 45, 47)
                || isValidVerse(curFile, vs, "1Sam-25.html#vs12")
                || isValidVerse(curFile, vs, "1Kgs-08.html#vs14")
                || isValidVerse(curFile, vs, "2Kgs-02.html#vs24")
                || isValidVerse(curFile, vs, "2Kgs-05.html#vs12")
                || isValidVerse(curFile, vs, "2Kgs-09.html#vs18", 19)
                || isValidVerse(curFile, vs, "2Chr-06.html#vs3")
                || isValidVerse(curFile, vs, "2Chr-20.html#vs27")
                || isValidVerse(curFile, vs, "Job-09.html#vs5")
                || isValidVerse(curFile, vs, "Job-12.html#vs15")
                || isValidVerse(curFile, vs, "Job-17.html#vs10")
                || isValidVerse(curFile, vs, "Job-28.html#vs9")
                || isValidVerse(curFile, vs, "Job-34.html#vs25")
                || isValidVerse(curFile, vs, "Job-39.html#vs25")
                || isValidVerse(curFile, vs, "Ps-078.html#vs9", 57)
                || isValidVerse(curFile, vs, "Song-2.html#vs17")
                || isValidVerse(curFile, vs, "Isa-38.html#vs2")
                || isValidVerse(curFile, vs, "Jer-41.html#vs14")
                || isValidVerse(curFile, vs, "Jer-46.html#vs5", 21)
                || isValidVerse(curFile, vs, "Jer-49.html#vs8", 24)
                || isValidVerse(curFile, vs, "Lam-1.html#vs20")
                || isValidVerse(curFile, vs, "Lam-2.html#vs14")
                || isValidVerse(curFile, vs, "Hos-11.html#vs8")
                || isValidVerse(curFile, vs, "Nah-2.html#vs8")
                || isValidVerse(curFile, vs, "Matt-09.html#vs22")
                || isValidVerse(curFile, vs, "Matt-16.html#vs23")
                || isValidVerse(curFile, vs, "Matt-21.html#vs12")
                || isValidVerse(curFile, vs, "Mark-05.html#vs30")
                || isValidVerse(curFile, vs, "Mark-08.html#vs33")
                || isValidVerse(curFile, vs, "Mark-11.html#vs15")
                || isValidVerse(curFile, vs, "Luke-07.html#vs9", 44)
                || isValidVerse(curFile, vs, "Luke-09.html#vs55")
                || isValidVerse(curFile, vs, "Luke-22.html#vs61")
                || isValidVerse(curFile, vs, "Luke-23.html#vs28")
                || isValidVerse(curFile, vs, "John-02.html#vs15")
                || isValidVerse(curFile, vs, "John-20.html#vs16")
                || isValidVerse(curFile, vs, "Acts-16.html#vs18")
                || isValidVerse(curFile, vs, "Rev-01.html#vs12");
    } // isOmkeren

    public static boolean isOnderstebovenKeren(final File curFile, final String vs) {
        return isValidVerse(curFile, vs, "Gen-19.html#vs21", 25, 29)
                || isValidVerse(curFile, vs, "Judg-07.html#vs13")
                || isValidVerse(curFile, vs, "2Sam-10.html#vs3")
                || isValidVerse(curFile, vs, "2Kgs-21.html#vs13")
                || isValidVerse(curFile, vs, "1Chr-19.html#vs3")
                || isValidVerse(curFile, vs, "Isa-01.html#vs7")
                || isValidVerse(curFile, vs, "Isa-13.html#vs19")
                || isValidVerse(curFile, vs, "Isa-24.html#vs1")
                || isValidVerse(curFile, vs, "Jer-20.html#vs16")
                || isValidVerse(curFile, vs, "Jer-49.html#vs18")
                || isValidVerse(curFile, vs, "Jer-50.html#vs40")
                || isValidVerse(curFile, vs, "Lam-4.html#vs6")
                || isValidVerse(curFile, vs, "Amos-4.html#vs11")
                || isValidVerse(curFile, vs, "Jonah-3.html#vs4");
    } // isOnderstebovenKeren

    public static boolean isTegenIetsKeren(final File curFile, final String vs) {
        return isValidVerse(curFile, vs, "Exod-14.html#vs5", 31)
                || isValidVerse(curFile, vs, "Exod-32.html#vs29")
                || isValidVerse(curFile, vs, "Lev-17.html#vs10")
                || isValidVerse(curFile, vs, "Lev-20.html#vs3",5, 6)
                || isValidVerse(curFile, vs, "Lev-26.html#vs17")
                || isValidVerse(curFile, vs, "Num-31.html#vs3")
                || isValidVerse(curFile, vs, "Deut-13.html#vs9")
                || isValidVerse(curFile, vs, "Deut-17.html#vs7")
                || isValidVerse(curFile, vs, "Josh-02.html#vs19")
                || isValidVerse(curFile, vs, "Josh-08.html#vs20")
                || isValidVerse(curFile, vs, "1Sam-15.html#vs2")
                || isValidVerse(curFile, vs, "2Sam-14.html#vs7")
                || isValidVerse(curFile, vs, "2Chr-28.html#vs12")
                || isValidVerse(curFile, vs, "Job-15.html#vs13")
                || isValidVerse(curFile, vs, "Job-17.html#vs8")
                || isValidVerse(curFile, vs, "Job-19.html#vs19")
                || isValidVerse(curFile, vs, "Job-30.html#vs15", 21)
                || isValidVerse(curFile, vs, "Ps-081.html#vs15")
                || isValidVerse(curFile, vs, "Eccl-10.html#vs4")
                || isValidVerse(curFile, vs, "Isa-01.html#vs25")
                || isValidVerse(curFile, vs, "Isa-41.html#vs12")
                || isValidVerse(curFile, vs, "Lam-3.html#vs3")
                || isValidVerse(curFile, vs, "Ezek-15.html#vs7")
                || isValidVerse(curFile, vs, "Ezek-19.html#vs8")
                || isValidVerse(curFile, vs, "Ezek-38.html#vs12")
                || isValidVerse(curFile, vs, "Hos-13.html#vs9")
                || isValidVerse(curFile, vs, "Amos-1.html#vs8")
                || isValidVerse(curFile, vs, "Jas-4.html#vs6")
                || isValidVerse(curFile, vs, "1Pet-5.html#vs5");
    } // isTegenIetsKeren

    public static boolean isTerugkeer(final File curFile, final String vs) {
        return isValidVerse(curFile, vs, "Isa-30.html#vs15");
    } // isTerugkeer

    public static boolean isTerugkeren(final File curFile, final String vs) {
        return isValidVerse(curFile, vs, "Gen-08.html#vs9", 12)
                || isValidVerse(curFile, vs, "Gen-14.html#vs7")
                || isValidVerse(curFile, vs, "Gen-16.html#vs9")
                || isValidVerse(curFile, vs, "Gen-18.html#vs33")
                || isValidVerse(curFile, vs, "Gen-21.html#vs32")
                || isValidVerse(curFile, vs, "Gen-22.html#vs19")
                || isValidVerse(curFile, vs, "Gen-26.html#vs18")
                || isValidVerse(curFile, vs, "Gen-31.html#vs3", 13, 55)
                || isValidVerse(curFile, vs, "Gen-32.html#vs9")
                || isValidVerse(curFile, vs, "Gen-37.html#vs30")
                || isValidVerse(curFile, vs, "Gen-38.html#vs22")
                || isValidVerse(curFile, vs, "Gen-42.html#vs24")
                || isValidVerse(curFile, vs, "Gen-43.html#vs2", 10)
                || isValidVerse(curFile, vs, "Gen-44.html#vs13", 25, 34)
                || isValidVerse(curFile, vs, "Gen-50.html#vs14")
                || isValidVerse(curFile, vs, "Exod-04.html#vs18", 19, 20)
                || isValidVerse(curFile, vs, "Exod-05.html#vs22")
                || isValidVerse(curFile, vs, "Exod-32.html#vs31")
                || isValidVerse(curFile, vs, "Exod-33.html#vs11")
                || isValidVerse(curFile, vs, "Exod-34.html#vs31")
                || isValidVerse(curFile, vs, "Lev-25.html#vs28")
                || isValidVerse(curFile, vs, "Num-10.html#vs36")
                || isValidVerse(curFile, vs, "Num-13.html#vs25")
                || isValidVerse(curFile, vs, "Num-14.html#vs3")
                || isValidVerse(curFile, vs, "Num-16.html#vs50")
                || isValidVerse(curFile, vs, "Num-23.html#vs5", 6, 16)
                || isValidVerse(curFile, vs, "Num-24.html#vs25")
                || isValidVerse(curFile, vs, "Num-33.html#vs7")
                || isValidVerse(curFile, vs, "Num-35.html#vs32")
                || isValidVerse(curFile, vs, "Deut-05.html#vs30")
                || isValidVerse(curFile, vs, "Josh-02.html#vs23")
                || isValidVerse(curFile, vs, "Josh-06.html#vs14")
                || isValidVerse(curFile, vs, "Josh-07.html#vs3")
                || isValidVerse(curFile, vs, "Josh-10.html#vs15", 43)
                || isValidVerse(curFile, vs, "Josh-11.html#vs10")
                || isValidVerse(curFile, vs, "Josh-22.html#vs4", 8, 9, 32)
                || isValidVerse(curFile, vs, "Judg-03.html#vs19")
                || isValidVerse(curFile, vs, "Judg-07.html#vs3", 15)
                || isValidVerse(curFile, vs, "Judg-14.html#vs19")
                || isValidVerse(curFile, vs, "Judg-20.html#vs48")
                || isValidVerse(curFile, vs, "Judg-21.html#vs23")
                || isValidVerse(curFile, vs, "Ruth-1.html#vs6", 7, 8, 10, 11, 12, 15, 22)
                || isValidVerse(curFile, vs, "1Sam-01.html#vs19")
                || isValidVerse(curFile, vs, "1Sam-06.html#vs16")
                || isValidVerse(curFile, vs, "1Sam-07.html#vs17")
                || isValidVerse(curFile, vs, "1Sam-15.html#vs25", 30, 31)
                || isValidVerse(curFile, vs, "1Sam-17.html#vs15", 53)
                || isValidVerse(curFile, vs, "1Sam-18.html#vs16")
                || isValidVerse(curFile, vs, "1Sam-23.html#vs28")
                || isValidVerse(curFile, vs, "1Sam-26.html#vs21", 25)
                || isValidVerse(curFile, vs, "1Sam-29.html#vs7", 11)
                || isValidVerse(curFile, vs, "2Sam-03.html#vs16")
                || isValidVerse(curFile, vs, "2Sam-10.html#vs14")
                || isValidVerse(curFile, vs, "2Sam-11.html#vs4")
                || isValidVerse(curFile, vs, "2Sam-12.html#vs31")
                || isValidVerse(curFile, vs, "2Sam-14.html#vs24")
                || isValidVerse(curFile, vs, "2Sam-15.html#vs19", 20, 27)
                || isValidVerse(curFile, vs, "2Sam-17.html#vs20")
                || isValidVerse(curFile, vs, "2Sam-18.html#vs16")
                || isValidVerse(curFile, vs, "2Sam-19.html#vs14", 15, 39)
                || isValidVerse(curFile, vs, "2Sam-20.html#vs22")
                || isValidVerse(curFile, vs, "2Sam-22.html#vs38")
                || isValidVerse(curFile, vs, "2Sam-23.html#vs10")
                || isValidVerse(curFile, vs, "1Kgs-10.html#vs13")
                || isValidVerse(curFile, vs, "1Kgs-12.html#vs24")
                || isValidVerse(curFile, vs, "1Kgs-13.html#vs10", 19, 33)
                || isValidVerse(curFile, vs, "1Kgs-17.html#vs22")
                || isValidVerse(curFile, vs, "1Kgs-19.html#vs15", 20, 21)
                || isValidVerse(curFile, vs, "2Kgs-01.html#vs6")
                || isValidVerse(curFile, vs, "2Kgs-02.html#vs13", 25)
                || isValidVerse(curFile, vs, "2Kgs-03.html#vs27")
                || isValidVerse(curFile, vs, "2Kgs-04.html#vs31")
                || isValidVerse(curFile, vs, "2Kgs-05.html#vs15", 25)
                || isValidVerse(curFile, vs, "2Kgs-07.html#vs8", 15)
                || isValidVerse(curFile, vs, "2Kgs-08.html#vs29")
                || isValidVerse(curFile, vs, "2Kgs-14.html#vs14")
                || isValidVerse(curFile, vs, "2Kgs-15.html#vs20")
                || isValidVerse(curFile, vs, "2Kgs-19.html#vs8", 36)
                || isValidVerse(curFile, vs, "2Kgs-20.html#vs5")
                || isValidVerse(curFile, vs, "2Kgs-23.html#vs20")
                || isValidVerse(curFile, vs, "1Chr-16.html#vs43")
                || isValidVerse(curFile, vs, "1Chr-20.html#vs3")
                || isValidVerse(curFile, vs, "2Chr-09.html#vs12")
                || isValidVerse(curFile, vs, "2Chr-11.html#vs4")
                || isValidVerse(curFile, vs, "2Chr-14.html#vs15")
                || isValidVerse(curFile, vs, "2Chr-19.html#vs1")
                || isValidVerse(curFile, vs, "2Chr-20.html#vs27")
                || isValidVerse(curFile, vs, "2Chr-22.html#vs6")
                || isValidVerse(curFile, vs, "2Chr-25.html#vs10", 24)
                || isValidVerse(curFile, vs, "2Chr-28.html#vs15")
                || isValidVerse(curFile, vs, "2Chr-31.html#vs1")
                || isValidVerse(curFile, vs, "2Chr-34.html#vs7")
                || isValidVerse(curFile, vs, "Neh-09.html#vs17")
                || isValidVerse(curFile, vs, "Esth-02.html#vs14")
                || isValidVerse(curFile, vs, "Esth-06.html#vs12")
                || isValidVerse(curFile, vs, "Job-07.html#vs10")
                || isValidVerse(curFile, vs, "Job-10.html#vs16")
                || isValidVerse(curFile, vs, "Ps-006.html#vs5")
                || isValidVerse(curFile, vs, "Ps-009.html#vs18")
                || isValidVerse(curFile, vs, "Ps-018.html#vs38")
                || isValidVerse(curFile, vs, "Ps-059.html#vs7")
                || isValidVerse(curFile, vs, "Ps-060.html#vs3")
                || isValidVerse(curFile, vs, "Ps-078.html#vs34")
                || isValidVerse(curFile, vs, "Ps-080.html#vs15")
                || isValidVerse(curFile, vs, "Ps-090.html#vs3", 13)
                || isValidVerse(curFile, vs, "Ps-104.html#vs29")
                || isValidVerse(curFile, vs, "Ps-116.html#vs7")
                || isValidVerse(curFile, vs, "Ps-126.html#vs1")
                || isValidVerse(curFile, vs, "Ps-146.html#vs4")
                || isValidVerse(curFile, vs, "Prov-12.html#vs14")
                || isValidVerse(curFile, vs, "Eccl-01.html#vs6", 7)
                || isValidVerse(curFile, vs, "Eccl-03.html#vs20")
                || isValidVerse(curFile, vs, "Song-6.html#vs13")
                || isValidVerse(curFile, vs, "Isa-21.html#vs12")
                || isValidVerse(curFile, vs, "Isa-37.html#vs8", 37)
                || isValidVerse(curFile, vs, "Isa-44.html#vs22")
                || isValidVerse(curFile, vs, "Isa-63.html#vs17")
                || isValidVerse(curFile, vs, "Jer-03.html#vs7",12, 14, 22)
                || isValidVerse(curFile, vs, "Jer-08.html#vs5")
                || isValidVerse(curFile, vs, "Jer-14.html#vs3")
                || isValidVerse(curFile, vs, "Jer-22.html#vs27")
                || isValidVerse(curFile, vs, "Jer-31.html#vs21")
                || isValidVerse(curFile, vs, "Jer-37.html#vs7")
                || isValidVerse(curFile, vs, "Jer-40.html#vs12")
                || isValidVerse(curFile, vs, "Jer-44.html#vs14")
                || isValidVerse(curFile, vs, "Jer-47.html#vs6")
                || isValidVerse(curFile, vs, "Jer-50.html#vs9")
                || isValidVerse(curFile, vs, "Ezek-18.html#vs30")
                || isValidVerse(curFile, vs, "Hos-02.html#vs6", 8)
                || isValidVerse(curFile, vs, "Hos-05.html#vs15")
                || isValidVerse(curFile, vs, "Hos-07.html#vs16")
                || isValidVerse(curFile, vs, "Hos-09.html#vs3")
                || isValidVerse(curFile, vs, "Mic-1.html#vs7")
                || isValidVerse(curFile, vs, "Zech-01.html#vs3")
                || isValidVerse(curFile, vs, "Zech-09.html#vs12")
                || isValidVerse(curFile, vs, "Mal-3.html#vs7")
                || isValidVerse(curFile, vs, "Matt-02.html#vs12")
                || isValidVerse(curFile, vs, "Matt-04.html#vs12")
                || isValidVerse(curFile, vs, "Luke-01.html#vs56")
                || isValidVerse(curFile, vs, "Luke-02.html#vs20", 39, 45)
                || isValidVerse(curFile, vs, "Luke-04.html#vs1", 14)
                || isValidVerse(curFile, vs, "Luke-08.html#vs37", 39, 55)
                || isValidVerse(curFile, vs, "Luke-17.html#vs15")
                || isValidVerse(curFile, vs, "Luke-19.html#vs12")
                || isValidVerse(curFile, vs, "Luke-23.html#vs48")
                || isValidVerse(curFile, vs, "Luke-24.html#vs33", 52)
                || isValidVerse(curFile, vs, "Acts-01.html#vs12")
                || isValidVerse(curFile, vs, "Acts-05.html#vs22")
                || isValidVerse(curFile, vs, "Acts-07.html#vs39")
                || isValidVerse(curFile, vs, "Acts-08.html#vs25", 28)
                || isValidVerse(curFile, vs, "Acts-12.html#vs25")
                || isValidVerse(curFile, vs, "Acts-13.html#vs13", 34)
                || isValidVerse(curFile, vs, "Acts-14.html#vs21")
                || isValidVerse(curFile, vs, "Acts-20.html#vs3")
                || isValidVerse(curFile, vs, "Acts-21.html#vs6")
                || isValidVerse(curFile, vs, "Acts-23.html#vs32")
                || isValidVerse(curFile, vs, "Gal-1.html#vs17")
                || isValidVerse(curFile, vs, "Heb-11.html#vs15");
    } // isTerugkeren

    public static boolean isToekeren(final File curFile, final String vs) {
        return isValidVerse(curFile, vs, "2Chr-26.html#vs20")
                || isValidVerse(curFile, vs, "Jer-02.html#vs27")
                || isValidVerse(curFile, vs, "Jer-32.html#vs33")
                || isValidVerse(curFile, vs, "Matt-05.html#vs39")
                || isValidVerse(curFile, vs, "Didache-01.html#vs4");
    } // isToekeren

    public static boolean isUitkeren(final File curFile, final String vs) {
        return isValidVerse(curFile, vs, "Job-31.html#vs39");
    } // isUitkeren

    private static boolean isKeren(final File curFile, final String vs) {
        return !isAfkeer(curFile, vs)
                && !isAfkeren(curFile, vs)
                && !isKeer(curFile, vs)
                && !isOmkeer(curFile, vs)
                && !isOmkeren(curFile, vs)
                && !isOnderstebovenKeren(curFile, vs)
                && !isTegenIetsKeren(curFile, vs)
                && !isTerugkeer(curFile, vs)
                && !isTerugkeren(curFile, vs)
                && !isToekeren(curFile, vs)
                && !isUitkeren(curFile, vs);
    }  // isKeren

}
