package rb.hsv.appendix.ccd.valid;

import org.jetbrains.annotations.NotNull;

import java.io.File;

import static rb.hsv.appendix.ccd.valid.util.ValidUtil.isValidVerse;

public class ValidDalen {

    public static boolean isValid(final @NotNull String keyArg, final File curFile, final String vs) {
        return switch (keyArg) {
            case "afdalen" -> isAfdalen(curFile, vs);
            case "dal" -> isDal(curFile, vs);
            case "neerdalen" -> isNeerdalen(curFile, vs);
            case "dalen" -> isDalen(curFile, vs);
            default -> true;
        };
    }

    public static boolean isAfdalen(final File curFile, final String vs) {
        return isValidVerse(curFile, vs, "Gen-24.html#vs16", 45)
                || isValidVerse(curFile, vs, "Exod-02.html#vs5")
                || isValidVerse(curFile, vs, "Exod-19.html#vs14", 24, 25)
                || isValidVerse(curFile, vs, "Exod-32.html#vs7", 15)
                || isValidVerse(curFile, vs, "Num-16.html#vs33")
                || isValidVerse(curFile, vs, "Num-20.html#vs28")
                || isValidVerse(curFile, vs, "Deut-01.html#vs25")
                || isValidVerse(curFile, vs, "Deut-09.html#vs12", 15)
                || isValidVerse(curFile, vs, "Deut-10.html#vs5")
                || isValidVerse(curFile, vs, "Josh-02.html#vs23")
                || isValidVerse(curFile, vs, "Josh-15.html#vs10")
                || isValidVerse(curFile, vs, "Judg-01.html#vs34")
                || isValidVerse(curFile, vs, "Judg-03.html#vs27", 28)
                || isValidVerse(curFile, vs, "Judg-04.html#vs14")
                || isValidVerse(curFile, vs, "Judg-05.html#vs11", 13, 14)
                || isValidVerse(curFile, vs, "Judg-07.html#vs9", 10, 11, 24)
                || isValidVerse(curFile, vs, "Judg-11.html#vs37")
                || isValidVerse(curFile, vs, "1Sam-09.html#vs25")
                || isValidVerse(curFile, vs, "2Sam-05.html#vs17")
                || isValidVerse(curFile, vs, "1Kgs-01.html#vs38")
                || isValidVerse(curFile, vs, "1Kgs-18.html#vs44")
                || isValidVerse(curFile, vs, "1Kgs-21.html#vs16", 18)
                || isValidVerse(curFile, vs, "2Kgs-05.html#vs14")
                || isValidVerse(curFile, vs, "Job-21.html#vs13")
                || isValidVerse(curFile, vs, "Prov-05.html#vs5")
                || isValidVerse(curFile, vs, "Prov-18.html#vs8")
                || isValidVerse(curFile, vs, "Prov-26.html#vs22")
                || isValidVerse(curFile, vs, "Song-4.html#vs8")
                || isValidVerse(curFile, vs, "Isa-15.html#vs3")
                || isValidVerse(curFile, vs, "Isa-30.html#vs2")
                || isValidVerse(curFile, vs, "Isa-47.html#vs1")
                || isValidVerse(curFile, vs, "Isa-52.html#vs4")
                || isValidVerse(curFile, vs, "Jer-18.html#vs2", 3)
                || isValidVerse(curFile, vs, "Jer-22.html#vs1")
                || isValidVerse(curFile, vs, "Jer-36.html#vs12")
                || isValidVerse(curFile, vs, "Jer-48.html#vs18")
                || isValidVerse(curFile, vs, "Ezek-27.html#vs29")
                || isValidVerse(curFile, vs, "Joel-3.html#vs13")
                || isValidVerse(curFile, vs, "Amos-6.html#vs2")
                || isValidVerse(curFile, vs, "Jonah-1.html#vs3")
                || isValidVerse(curFile, vs, "Jonah-2.html#vs6")
                || isValidVerse(curFile, vs, "Mic-1.html#vs3")
                || isValidVerse(curFile, vs, "Luke-04.html#vs31")
                || isValidVerse(curFile, vs, "John-05.html#vs7")
                || isValidVerse(curFile, vs, "John-06.html#vs16")
                || isValidVerse(curFile, vs, "Acts-08.html#vs5", 38);
    } // isAfdalen

    public static boolean isDal(final File curFile, final String vs) {
        return isValidVerse(curFile, vs, "Gen-14.html#vs17")
                || isValidVerse(curFile, vs, "Gen-26.html#vs17", 19)
                || isValidVerse(curFile, vs, "Gen-37.html#vs14")
                || isValidVerse(curFile, vs, "Num-13.html#vs23", 24)
                || isValidVerse(curFile, vs, "Num-14.html#vs25")
                || isValidVerse(curFile, vs, "Num-21.html#vs14", 15, 20)
                || isValidVerse(curFile, vs, "Num-32.html#vs9")
                || isValidVerse(curFile, vs, "Deut-01.html#vs24")
                || isValidVerse(curFile, vs, "Deut-03.html#vs29")
                || isValidVerse(curFile, vs, "Deut-04.html#vs46")
                || isValidVerse(curFile, vs, "Deut-08.html#vs7")
                || isValidVerse(curFile, vs, "Deut-11.html#vs11")
                || isValidVerse(curFile, vs, "Deut-21.html#vs4", 6)
                || isValidVerse(curFile, vs, "Deut-34.html#vs6")
                || isValidVerse(curFile, vs, "Josh-07.html#vs24", 26)
                || isValidVerse(curFile, vs, "Josh-08.html#vs11", 13)
                || isValidVerse(curFile, vs, "Josh-10.html#vs12")
                || isValidVerse(curFile, vs, "Josh-11.html#vs8", 17)
                || isValidVerse(curFile, vs, "Josh-12.html#vs7")
                || isValidVerse(curFile, vs, "Josh-13.html#vs19", 27)
                || isValidVerse(curFile, vs, "Josh-15.html#vs7", 8)
                || isValidVerse(curFile, vs, "Josh-17.html#vs16")
                || isValidVerse(curFile, vs, "Josh-18.html#vs16")
                || isValidVerse(curFile, vs, "Josh-19.html#vs14", 27)
                || isValidVerse(curFile, vs, "Judg-01.html#vs19", 34)
                || isValidVerse(curFile, vs, "Judg-05.html#vs15")
                || isValidVerse(curFile, vs, "Judg-06.html#vs33")
                || isValidVerse(curFile, vs, "Judg-07.html#vs1", 8, 12)
                || isValidVerse(curFile, vs, "Judg-18.html#vs28")
                || isValidVerse(curFile, vs, "1Sam-06.html#vs13")
                || isValidVerse(curFile, vs, "1Sam-13.html#vs18")
                || isValidVerse(curFile, vs, "1Sam-15.html#vs5")
                || isValidVerse(curFile, vs, "1Sam-31.html#vs7")
                || isValidVerse(curFile, vs, "2Sam-05.html#vs18", 22)
                || isValidVerse(curFile, vs, "2Sam-17.html#vs13")
                || isValidVerse(curFile, vs, "2Sam-23.html#vs13", 30)
                || isValidVerse(curFile, vs, "2Sam-24.html#vs5")
                || isValidVerse(curFile, vs, "1Kgs-01.html#vs25")
                || isValidVerse(curFile, vs, "1Kgs-20.html#vs28")
                || isValidVerse(curFile, vs, "2Kgs-02.html#vs16")
                || isValidVerse(curFile, vs, "2Kgs-03.html#vs16", 17)
                || isValidVerse(curFile, vs, "2Kgs-23.html#vs10")
                || isValidVerse(curFile, vs, "1Chr-04.html#vs39")
                || isValidVerse(curFile, vs, "1Chr-10.html#vs7")
                || isValidVerse(curFile, vs, "1Chr-11.html#vs15", 32)
                || isValidVerse(curFile, vs, "1Chr-12.html#vs15")
                || isValidVerse(curFile, vs, "1Chr-14.html#vs9", 13)
                || isValidVerse(curFile, vs, "1Chr-27.html#vs29")
                || isValidVerse(curFile, vs, "2Chr-14.html#vs10")
                || isValidVerse(curFile, vs, "2Chr-20.html#vs16")
                || isValidVerse(curFile, vs, "2Chr-28.html#vs3")
                || isValidVerse(curFile, vs, "2Chr-33.html#vs6", 14)
                || isValidVerse(curFile, vs, "2Chr-35.html#vs22")
                || isValidVerse(curFile, vs, "Neh-06.html#vs2")
                || isValidVerse(curFile, vs, "Neh-11.html#vs30")
                || isValidVerse(curFile, vs, "Job-21.html#vs33")
                || isValidVerse(curFile, vs, "Job-30.html#vs6")
                || isValidVerse(curFile, vs, "Ps-023.html#vs4")
                || isValidVerse(curFile, vs, "Ps-060.html#vs8")
                || isValidVerse(curFile, vs, "Ps-065.html#vs14")
                || isValidVerse(curFile, vs, "Ps-084.html#vs7")
                || isValidVerse(curFile, vs, "Ps-104.html#vs8", 10)
                || isValidVerse(curFile, vs, "Ps-108.html#vs8")
                || isValidVerse(curFile, vs, "Song-2.html#vs1")
                || isValidVerse(curFile, vs, "Isa-07.html#vs19")
                || isValidVerse(curFile, vs, "Isa-17.html#vs5")
                || isValidVerse(curFile, vs, "Isa-22.html#vs1", 5, 7)
                || isValidVerse(curFile, vs, "Isa-28.html#vs21")
                || isValidVerse(curFile, vs, "Isa-40.html#vs4")
                || isValidVerse(curFile, vs, "Isa-57.html#vs6")
                || isValidVerse(curFile, vs, "Isa-65.html#vs10")
                || isValidVerse(curFile, vs, "Jer-02.html#vs23")
                || isValidVerse(curFile, vs, "Jer-07.html#vs31", 32)
                || isValidVerse(curFile, vs, "Jer-19.html#vs2", 6)
                || isValidVerse(curFile, vs, "Jer-21.html#vs13")
                || isValidVerse(curFile, vs, "Jer-31.html#vs40")
                || isValidVerse(curFile, vs, "Jer-32.html#vs35")
                || isValidVerse(curFile, vs, "Jer-47.html#vs5")
                || isValidVerse(curFile, vs, "Jer-48.html#vs8")
                || isValidVerse(curFile, vs, "Jer-49.html#vs4")
                || isValidVerse(curFile, vs, "Ezek-06.html#vs3")
                || isValidVerse(curFile, vs, "Ezek-07.html#vs16")
                || isValidVerse(curFile, vs, "Ezek-31.html#vs12")
                || isValidVerse(curFile, vs, "Ezek-32.html#vs5")
                || isValidVerse(curFile, vs, "Ezek-35.html#vs8")
                || isValidVerse(curFile, vs, "Ezek-36.html#vs4", 6)
                || isValidVerse(curFile, vs, "Ezek-39.html#vs11", 15)
                || isValidVerse(curFile, vs, "Dan-03.html#vs1")
                || isValidVerse(curFile, vs, "Hos-01.html#vs5")
                || isValidVerse(curFile, vs, "Hos-02.html#vs14")
                || isValidVerse(curFile, vs, "Joel-3.html#vs2", 12, 14, 18)
                || isValidVerse(curFile, vs, "Mic-1.html#vs4", 6)
                || isValidVerse(curFile, vs, "Zech-12.html#vs11")
                || isValidVerse(curFile, vs, "Zech-14.html#vs4", 5)
                || isValidVerse(curFile, vs, "Luke-03.html#vs5");
    } // isDal

    public static boolean isNeerdalen(final File curFile, final String vs) {
        return isValidVerse(curFile, vs, "Gen-11.html#vs5")
                || isValidVerse(curFile, vs, "Exod-19.html#vs20")
                || isValidVerse(curFile, vs, "Exod-34.html#vs5")
                || isValidVerse(curFile, vs, "Num-11.html#vs9", 25)
                || isValidVerse(curFile, vs, "Num-12.html#vs5")
                || isValidVerse(curFile, vs, "2Sam-22.html#vs10")
                || isValidVerse(curFile, vs, "Ps-018.html#vs10")
                || isValidVerse(curFile, vs, "Ps-104.html#vs8")
                || isValidVerse(curFile, vs, "Ps-107.html#vs26")
                || isValidVerse(curFile, vs, "Ps-144.html#vs5")
                || isValidVerse(curFile, vs, "Isa-05.html#vs14")
                || isValidVerse(curFile, vs, "Isa-64.html#vs3")
                || isValidVerse(curFile, vs, "Ezek-32.html#vs19")
                || isValidVerse(curFile, vs, "Dan-04.html#vs13")
                || isValidVerse(curFile, vs, "John-05.html#vs4")
                || isValidVerse(curFile, vs, "Acts-11.html#vs5")
                || isValidVerse(curFile, vs, "Jas-1.html#vs17")
                || isValidVerse(curFile, vs, "Rev-20.html#vs9");
    } // isNeerdalen

    private static boolean isDalen(final File curFile, final String vs) {
        return !isAfdalen(curFile, vs)
                && !isDal(curFile, vs)
                && !isNeerdalen(curFile, vs);
    }  // isDalen

}
