package rb.hsv.appendix.ccd.valid;

import java.io.File;

import static rb.hsv.appendix.ccd.valid.util.ValidUtil.isValidVerse;

public class ValidAchten {

    public static boolean isValid(final String keyArg, final String arg, final File curFile, final String vs) {
        return switch (keyArg) {
            case "acht" -> isAchtGetal(curFile, vs);
            case "acht geven" -> isAchtGeven(curFile, vs);
            case "acht slaan op" -> isAchtSlaanOp(curFile, vs, arg);
            case "hoogachten" -> isHoogachten(curFile, vs);
            case "in acht nemen" -> isInAchtNemen(curFile, vs, arg);
            case "achten" -> isAchten(curFile, vs, arg);
            default -> true;
        };
    }

    public static boolean isAchtGetal(final File curFile, final String vs) {
        return isValidVerse(curFile, vs, "Gen-17.html#vs12")
                || isValidVerse(curFile, vs, "Gen-21.html#vs4")
                || isValidVerse(curFile, vs, "Gen-22.html#vs23")
                || isValidVerse(curFile, vs, "Exod-22.html#vs30")
                || isValidVerse(curFile, vs, "Exod-26.html#vs25")
                || isValidVerse(curFile, vs, "Exod-36.html#vs30")
                || isValidVerse(curFile, vs, "Lev-09.html#vs1")
                || isValidVerse(curFile, vs, "Lev-12.html#vs3")
                || isValidVerse(curFile, vs, "Lev-14.html#vs10", 23)
                || isValidVerse(curFile, vs, "Lev-15.html#vs14", 29)
                || isValidVerse(curFile, vs, "Lev-22.html#vs27")
                || isValidVerse(curFile, vs, "Lev-23.html#vs36", 39)
                || isValidVerse(curFile, vs, "Lev-25.html#vs22")
                || isValidVerse(curFile, vs, "Num-06.html#vs10")
                || isValidVerse(curFile, vs, "Num-07.html#vs8", 54)
                || isValidVerse(curFile, vs, "Num-29.html#vs29", 35)
                || isValidVerse(curFile, vs, "Judg-03.html#vs8")
                || isValidVerse(curFile, vs, "Judg-12.html#vs14")
                || isValidVerse(curFile, vs, "1Sam-17.html#vs12")
                || isValidVerse(curFile, vs, "1Kgs-06.html#vs38")
                || isValidVerse(curFile, vs, "1Kgs-07.html#vs10")
                || isValidVerse(curFile, vs, "1Kgs-08.html#vs66")
                || isValidVerse(curFile, vs, "1Kgs-12.html#vs32", 33)
                || isValidVerse(curFile, vs, "2Kgs-08.html#vs17")
                || isValidVerse(curFile, vs, "2Kgs-22.html#vs1")
                || isValidVerse(curFile, vs, "2Kgs-24.html#vs12")
                || isValidVerse(curFile, vs, "1Chr-12.html#vs12")
                || isValidVerse(curFile, vs, "1Chr-24.html#vs4", 10)
                || isValidVerse(curFile, vs, "1Chr-25.html#vs15")
                || isValidVerse(curFile, vs, "1Chr-26.html#vs5")
                || isValidVerse(curFile, vs, "1Chr-27.html#vs11")
                || isValidVerse(curFile, vs, "2Chr-07.html#vs9")
                || isValidVerse(curFile, vs, "2Chr-21.html#vs5", 20)
                || isValidVerse(curFile, vs, "2Chr-29.html#vs17")
                || isValidVerse(curFile, vs, "2Chr-34.html#vs1", 3)
                || isValidVerse(curFile, vs, "2Chr-36.html#vs9")
                || isValidVerse(curFile, vs, "Neh-08.html#vs19")
                || isValidVerse(curFile, vs, "Ps-006.html#vs1")
                || isValidVerse(curFile, vs, "Ps-012.html#vs1")
                || isValidVerse(curFile, vs, "Eccl-11.html#vs2")
                || isValidVerse(curFile, vs, "Jer-41.html#vs15")
                || isValidVerse(curFile, vs, "Ezek-40.html#vs9", 31, 34, 37, 41)
                || isValidVerse(curFile, vs, "Ezek-43.html#vs27")
                || isValidVerse(curFile, vs, "Mic-5.html#vs4")
                || isValidVerse(curFile, vs, "Zech-01.html#vs1")
                || isValidVerse(curFile, vs, "Luke-01.html#vs59")
                || isValidVerse(curFile, vs, "Luke-02.html#vs21")
                || isValidVerse(curFile, vs, "Luke-09.html#vs28")
                || isValidVerse(curFile, vs, "John-20.html#vs26")
                || isValidVerse(curFile, vs, "Acts-07.html#vs8")
                || isValidVerse(curFile, vs, "Acts-09.html#vs33")
                || isValidVerse(curFile, vs, "Phil-3.html#vs5")
                || isValidVerse(curFile, vs, "1Pet-3.html#vs20")
                || isValidVerse(curFile, vs, "Rev-17.html#vs11")
                || isValidVerse(curFile, vs, "Rev-21.html#vs20");
    }  // isAchtGetal

    public static boolean isAchtGeven(final File curFile, final String vs) {
        return isValidVerse(curFile, vs, "Acts-16.html#vs14")
                || isValidVerse(curFile, vs, "1Tim-4.html#vs16")
                || isValidVerse(curFile, vs, "Rev-16.html#vs15");
    }  // isAchtGeven

    public static boolean isAchtSlaanOp(final File curFile, final String vs, final String arg) {
        if (arg.equals("acht slaan op")) {
            return false;
        }
        return isValidVerse(curFile, vs, "Gen-04.html#vs4", 5)
                || isValidVerse(curFile, vs, "1Sam-15.html#vs2")
                || isValidVerse(curFile, vs, "2Chr-20.html#vs15")
                || isValidVerse(curFile, vs, "2Chr-33.html#vs10")
                || isValidVerse(curFile, vs, "Neh-09.html#vs34")
                || isValidVerse(curFile, vs, "Job-01.html#vs8")
                || isValidVerse(curFile, vs, "Job-02.html#vs3")
                || isValidVerse(curFile, vs, "Job-09.html#vs21")
                || isValidVerse(curFile, vs, "Job-13.html#vs6")
                || isValidVerse(curFile, vs, "Job-23.html#vs6")
                || isValidVerse(curFile, vs, "Job-33.html#vs14", 31)
                || isValidVerse(curFile, vs, "Ps-005.html#vs3")
                || isValidVerse(curFile, vs, "Ps-010.html#vs17")
                || isValidVerse(curFile, vs, "Ps-017.html#vs1")
                || isValidVerse(curFile, vs, "Ps-055.html#vs3")
                || isValidVerse(curFile, vs, "Ps-061.html#vs2")
                || isValidVerse(curFile, vs, "Ps-066.html#vs19")
                || isValidVerse(curFile, vs, "Ps-086.html#vs6")
                || isValidVerse(curFile, vs, "Ps-142.html#vs7")
                || isValidVerse(curFile, vs, "Prov-01.html#vs24")
                || isValidVerse(curFile, vs, "Prov-02.html#vs2")
                || isValidVerse(curFile, vs, "Prov-04.html#vs1", 20)
                || isValidVerse(curFile, vs, "Prov-05.html#vs1")
                || isValidVerse(curFile, vs, "Prov-07.html#vs24")
                || isValidVerse(curFile, vs, "Prov-17.html#vs4")
                || isValidVerse(curFile, vs, "Prov-29.html#vs12")
                || isValidVerse(curFile, vs, "Song-8.html#vs13")
                || isValidVerse(curFile, vs, "Isa-10.html#vs30")
                || isValidVerse(curFile, vs, "Isa-28.html#vs23")
                || isValidVerse(curFile, vs, "Isa-31.html#vs1")
                || isValidVerse(curFile, vs, "Isa-32.html#vs3")
                || isValidVerse(curFile, vs, "Isa-34.html#vs1")
                || isValidVerse(curFile, vs, "Isa-42.html#vs23")
                || isValidVerse(curFile, vs, "Isa-48.html#vs18")
                || isValidVerse(curFile, vs, "Isa-49.html#vs1")
                || isValidVerse(curFile, vs, "Isa-51.html#vs4")
                || isValidVerse(curFile, vs, "Jer-06.html#vs10", 17, 19)
                || isValidVerse(curFile, vs, "Jer-08.html#vs6")
                || isValidVerse(curFile, vs, "Jer-18.html#vs18", 19)
                || isValidVerse(curFile, vs, "Jer-23.html#vs18")
                || isValidVerse(curFile, vs, "Ezek-44.html#vs5")
                || isValidVerse(curFile, vs, "Dan-03.html#vs12")
                || isValidVerse(curFile, vs, "Dan-06.html#vs14")
                || isValidVerse(curFile, vs, "Dan-09.html#vs19")
                || isValidVerse(curFile, vs, "Hos-05.html#vs1")
                || isValidVerse(curFile, vs, "Mic-1.html#vs2")
                || isValidVerse(curFile, vs, "Zech-01.html#vs4")
                || isValidVerse(curFile, vs, "Zech-07.html#vs11")
                || isValidVerse(curFile, vs, "Mal-3.html#vs16")
                || isValidVerse(curFile, vs, "Matt-22.html#vs5")
                || isValidVerse(curFile, vs, "Luke-01.html#vs25")
                || isValidVerse(curFile, vs, "Acts-04.html#vs29")
                || isValidVerse(curFile, vs, "Heb-08.html#vs9")
                || isValidVerse(curFile, vs, "2Pet-1.html#vs19");
    }  // isAchtSlaan

    public static boolean isHoogachten(final File curFile, final String vs) {
        return isValidVerse(curFile, vs, "1Thess-5.html#vs13");
    }  // isHoogachten

    public static boolean isInAchtNemen(final File curFile, final String vs, final String arg) {
        if (arg.equals("in acht nemen")) {
            return false;
        }
        return isValidVerse(curFile, vs, "Gen-17.html#vs9")
                || isValidVerse(curFile, vs, "Gen-18.html#vs19")
                || isValidVerse(curFile, vs, "Gen-26.html#vs5")
                || isValidVerse(curFile, vs, "Exod-12.html#vs17", 25)
                || isValidVerse(curFile, vs, "Exod-13.html#vs10")
                || isValidVerse(curFile, vs, "Exod-15.html#vs26")
                || isValidVerse(curFile, vs, "Exod-16.html#vs28")
                || isValidVerse(curFile, vs, "Exod-19.html#vs5")
                || isValidVerse(curFile, vs, "Exod-20.html#vs6")
                || isValidVerse(curFile, vs, "Exod-23.html#vs15")
                || isValidVerse(curFile, vs, "Exod-31.html#vs13", 14, 16)
                || isValidVerse(curFile, vs, "Exod-34.html#vs18")
                || isValidVerse(curFile, vs, "Lev-08.html#vs35")
                || isValidVerse(curFile, vs, "Lev-18.html#vs4", 5, 26, 30)
                || isValidVerse(curFile, vs, "Lev-19.html#vs3", 19, 30, 37)
                || isValidVerse(curFile, vs, "Lev-20.html#vs22")
                || isValidVerse(curFile, vs, "Lev-22.html#vs9", 31)
                || isValidVerse(curFile, vs, "Lev-25.html#vs18")
                || isValidVerse(curFile, vs, "Lev-26.html#vs2", 3)
                || isValidVerse(curFile, vs, "Num-01.html#vs53")
                || isValidVerse(curFile, vs, "Num-09.html#vs19", 23)
                || isValidVerse(curFile, vs, "Deut-04.html#vs2", 6, 9, 40)
                || isValidVerse(curFile, vs, "Deut-05.html#vs1", 10, 12, 29)
                || isValidVerse(curFile, vs, "Deut-06.html#vs2", 3, 17, 25)
                || isValidVerse(curFile, vs, "Deut-07.html#vs8", 8, 9, 11, 12)
                || isValidVerse(curFile, vs, "Deut-08.html#vs1", 2, 6, 11)
                || isValidVerse(curFile, vs, "Deut-10.html#vs13")
                || isValidVerse(curFile, vs, "Deut-11.html#vs1", 8, 22, 32)
                || isValidVerse(curFile, vs, "Deut-12.html#vs1", 32)
                || isValidVerse(curFile, vs, "Deut-13.html#vs4", 18)
                || isValidVerse(curFile, vs, "Deut-15.html#vs5")
                || isValidVerse(curFile, vs, "Deut-16.html#vs1", 12)
                || isValidVerse(curFile, vs, "Deut-17.html#vs19")
                || isValidVerse(curFile, vs, "Deut-26.html#vs16", 17, 18)
                || isValidVerse(curFile, vs, "Deut-27.html#vs1")
                || isValidVerse(curFile, vs, "Deut-28.html#vs1", 9, 13, 45)
                || isValidVerse(curFile, vs, "Deut-30.html#vs10", 16)
                || isValidVerse(curFile, vs, "Deut-33.html#vs9")
                || isValidVerse(curFile, vs, "Josh-22.html#vs2", 3, 5)
                || isValidVerse(curFile, vs, "Josh-23.html#vs6")
                || isValidVerse(curFile, vs, "Judg-02.html#vs22")
                || isValidVerse(curFile, vs, "Judg-13.html#vs14")
                || isValidVerse(curFile, vs, "1Sam-13.html#vs13", 14)
                || isValidVerse(curFile, vs, "2Sam-22.html#vs22")
                || isValidVerse(curFile, vs, "1Kgs-02.html#vs3", 43)
                || isValidVerse(curFile, vs, "1Kgs-03.html#vs14")
                || isValidVerse(curFile, vs, "1Kgs-06.html#vs12")
                || isValidVerse(curFile, vs, "1Kgs-08.html#vs58", 61)
                || isValidVerse(curFile, vs, "1Kgs-09.html#vs4", 6)
                || isValidVerse(curFile, vs, "1Kgs-11.html#vs11", 34, 38)
                || isValidVerse(curFile, vs, "1Kgs-13.html#vs21")
                || isValidVerse(curFile, vs, "1Kgs-14.html#vs8")
                || isValidVerse(curFile, vs, "2Kgs-17.html#vs13", 19, 37)
                || isValidVerse(curFile, vs, "2Kgs-18.html#vs6")
                || isValidVerse(curFile, vs, "2Kgs-23.html#vs3")
                || isValidVerse(curFile, vs, "1Chr-10.html#vs13")
                || isValidVerse(curFile, vs, "1Chr-22.html#vs12", 13)
                || isValidVerse(curFile, vs, "1Chr-28.html#vs8")
                || isValidVerse(curFile, vs, "1Chr-29.html#vs19")
                || isValidVerse(curFile, vs, "2Chr-07.html#vs17")
                || isValidVerse(curFile, vs, "2Chr-23.html#vs6")
                || isValidVerse(curFile, vs, "2Chr-33.html#vs8")
                || isValidVerse(curFile, vs, "2Chr-34.html#vs21", 31)
                || isValidVerse(curFile, vs, "Neh-01.html#vs5", 7, 9)
                || isValidVerse(curFile, vs, "Neh-09.html#vs32")
                || isValidVerse(curFile, vs, "Neh-10.html#vs29")
                || isValidVerse(curFile, vs, "Ps-025.html#vs10")
                || isValidVerse(curFile, vs, "Ps-078.html#vs7", 10, 56)
                || isValidVerse(curFile, vs, "Ps-089.html#vs32")
                || isValidVerse(curFile, vs, "Ps-099.html#vs7")
                || isValidVerse(curFile, vs, "Ps-103.html#vs18")
                || isValidVerse(curFile, vs, "Ps-105.html#vs45")
                || isValidVerse(curFile, vs, "Ps-119.html#vs2", 4, 5, 8, 17, 22, 33, 34, 44, 55, 56, 57, 60, 63, 67, 69, 88, 100, 106, 115, 129, 134, 136, 145, 167, 168)
                || isValidVerse(curFile, vs, "Ps-132.html#vs12")
                || isValidVerse(curFile, vs, "Prov-02.html#vs8", 20)
                || isValidVerse(curFile, vs, "Prov-03.html#vs1", 21)
                || isValidVerse(curFile, vs, "Prov-04.html#vs4", 13)
                || isValidVerse(curFile, vs, "Prov-05.html#vs2")
                || isValidVerse(curFile, vs, "Prov-06.html#vs20")
                || isValidVerse(curFile, vs, "Prov-07.html#vs1", 2)
                || isValidVerse(curFile, vs, "Prov-08.html#vs32")
                || isValidVerse(curFile, vs, "Prov-10.html#vs17")
                || isValidVerse(curFile, vs, "Prov-13.html#vs18")
                || isValidVerse(curFile, vs, "Prov-15.html#vs5")
                || isValidVerse(curFile, vs, "Prov-16.html#vs17")
                || isValidVerse(curFile, vs, "Prov-19.html#vs16")
                || isValidVerse(curFile, vs, "Prov-28.html#vs4", 7)
                || isValidVerse(curFile, vs, "Eccl-08.html#vs5")
                || isValidVerse(curFile, vs, "Isa-56.html#vs1", 2, 4, 6)
                || isValidVerse(curFile, vs, "Jer-08.html#vs7")
                || isValidVerse(curFile, vs, "Jer-16.html#vs11")
                || isValidVerse(curFile, vs, "Jer-35.html#vs18")
                || isValidVerse(curFile, vs, "Ezek-11.html#vs20")
                || isValidVerse(curFile, vs, "Ezek-17.html#vs14")
                || isValidVerse(curFile, vs, "Ezek-18.html#vs9", 19, 21)
                || isValidVerse(curFile, vs, "Ezek-20.html#vs18", 19)
                || isValidVerse(curFile, vs, "Ezek-36.html#vs27")
                || isValidVerse(curFile, vs, "Ezek-37.html#vs24")
                || isValidVerse(curFile, vs, "Ezek-43.html#vs11")
                || isValidVerse(curFile, vs, "Ezek-44.html#vs24")
                || isValidVerse(curFile, vs, "Dan-09.html#vs4")
                || isValidVerse(curFile, vs, "Amos-2.html#vs4")
                || isValidVerse(curFile, vs, "Mal-2.html#vs9")
                || isValidVerse(curFile, vs, "Mal-3.html#vs7")
                || isValidVerse(curFile, vs, "Matt-19.html#vs17", 20)
                || isValidVerse(curFile, vs, "Matt-23.html#vs3")
                || isValidVerse(curFile, vs, "Matt-28.html#vs19")
                || isValidVerse(curFile, vs, "Mark-10.html#vs20")
                || isValidVerse(curFile, vs, "Luke-18.html#vs21")
                || isValidVerse(curFile, vs, "John-08.html#vs51", 52, 55)
                || isValidVerse(curFile, vs, "John-09.html#vs16")
                || isValidVerse(curFile, vs, "John-14.html#vs15",  21, 23, 24)
                || isValidVerse(curFile, vs, "John-15.html#vs10", 20)
                || isValidVerse(curFile, vs, "John-17.html#vs6")
                || isValidVerse(curFile, vs, "Acts-07.html#vs53")
                || isValidVerse(curFile, vs, "Acts-15.html#vs5")
                || isValidVerse(curFile, vs, "Acts-16.html#vs4")
                || isValidVerse(curFile, vs, "Acts-21.html#vs24", 25)
                || isValidVerse(curFile, vs, "Rom-02.html#vs26")
                || isValidVerse(curFile, vs, "1Cor-07.html#vs19")
                || isValidVerse(curFile, vs, "Gal-6.html#vs13")
                || isValidVerse(curFile, vs, "1Tim-5.html#vs21")
                || isValidVerse(curFile, vs, "1Tim-6.html#vs14")
                || isValidVerse(curFile, vs, "2Tim-2.html#vs5")
                || isValidVerse(curFile, vs, "Jas-2.html#vs10")
                || isValidVerse(curFile, vs, "1John-2.html#vs3", 4, 5)
                || isValidVerse(curFile, vs, "1John-3.html#vs22", 24)
                || isValidVerse(curFile, vs, "1John-5.html#vs3")
                || isValidVerse(curFile, vs, "Rev-01.html#vs3")
                || isValidVerse(curFile, vs, "Rev-02.html#vs26")
                || isValidVerse(curFile, vs, "Rev-03.html#vs8")
                || isValidVerse(curFile, vs, "Rev-12.html#vs17")
                || isValidVerse(curFile, vs, "Rev-14.html#vs12")
                || isValidVerse(curFile, vs, "Rev-22.html#vs7", 9);
    }  // isInAchtNemen

    public static boolean isAchten(final File curFile, final String vs, final String arg) {
        return !isAchtGetal(curFile, vs)
                && !isAchtGeven(curFile, vs)
                && !isAchtSlaanOp(curFile, vs, arg)
                && !isHoogachten(curFile, vs)
                && !isInAchtNemen(curFile, vs, arg);
    }  // isAchten

}
