package rb.hsv.appendix.ccd.valid;

import org.jetbrains.annotations.NotNull;

import java.io.File;

import static rb.hsv.appendix.ccd.valid.util.ValidUtil.isValidVerse;

public class ValidGebieden {

    public static boolean isValid(final @NotNull String keyArg, final String arg, final File curFile, final String vs) {
        return switch (keyArg) {
            case "gebied" -> isGebied(curFile, vs);
            case "gebieden" -> isGebieden(curFile, vs, arg);
            case "gebod" -> isGebod(curFile, vs, arg);
            default -> true;
        };
    }

    private static boolean isZowelGebiedAlsGebieden(final File curFile, final String vs) {
        return isValidVerse(curFile, vs, "Deut-02.html#vs4");
    } // isZowelGebiedAlsGebieden

    public static boolean isGebied(final File curFile, final String vs) {
        return isZowelGebiedAlsGebieden(curFile, vs)
                || isValidVerse(curFile, vs, "Gen-14.html#vs7")
                || isValidVerse(curFile, vs, "Gen-19.html#vs28")
                || isValidVerse(curFile, vs, "Gen-23.html#vs17")
                || isValidVerse(curFile, vs, "Gen-32.html#vs3")
                || isValidVerse(curFile, vs, "Gen-47.html#vs21")
                || isValidVerse(curFile, vs, "Exod-03.html#vs8")
                || isValidVerse(curFile, vs, "Exod-08.html#vs2")
                || isValidVerse(curFile, vs, "Exod-10.html#vs14")
                || isValidVerse(curFile, vs, "Exod-13.html#vs7")
                || isValidVerse(curFile, vs, "Exod-16.html#vs35")
                || isValidVerse(curFile, vs, "Exod-34.html#vs24")
                || isValidVerse(curFile, vs, "Lev-16.html#vs22")
                || isValidVerse(curFile, vs, "Num-20.html#vs17", 21)
                || isValidVerse(curFile, vs, "Num-21.html#vs13", 15, 22, 23, 24)
                || isValidVerse(curFile, vs, "Num-22.html#vs36")
                || isValidVerse(curFile, vs, "Num-32.html#vs33")
                || isValidVerse(curFile, vs, "Deut-02.html#vs37")
                || isValidVerse(curFile, vs, "Deut-03.html#vs4", 13, 14, 16, 17)
                || isValidVerse(curFile, vs, "Deut-04.html#vs48")
                || isValidVerse(curFile, vs, "Deut-11.html#vs24")
                || isValidVerse(curFile, vs, "Deut-12.html#vs20")
                || isValidVerse(curFile, vs, "Deut-16.html#vs4")
                || isValidVerse(curFile, vs, "Deut-19.html#vs3", 8)
                || isValidVerse(curFile, vs, "Deut-29.html#vs16")
                || isValidVerse(curFile, vs, "Deut-32.html#vs9")
                || isValidVerse(curFile, vs, "Josh-01.html#vs4")
                || isValidVerse(curFile, vs, "Josh-12.html#vs2", 4, 5)
                || isValidVerse(curFile, vs, "Josh-13.html#vs2", 3, 4, 10, 11, 16, 23, 25, 26, 27, 30)
                || isValidVerse(curFile, vs, "Josh-15.html#vs12", 21, 47)
                || isValidVerse(curFile, vs, "Josh-16.html#vs2", 3, 5)
                || isValidVerse(curFile, vs, "Josh-18.html#vs5", 11, 20)
                || isValidVerse(curFile, vs, "Josh-19.html#vs9", 10, 12, 18, 25, 41, 46, 47)
                || isValidVerse(curFile, vs, "Josh-22.html#vs10", 11)
                || isValidVerse(curFile, vs, "Josh-24.html#vs30")
                || isValidVerse(curFile, vs, "Judg-01.html#vs3", 18, 36)
                || isValidVerse(curFile, vs, "Judg-02.html#vs9")
                || isValidVerse(curFile, vs, "Judg-11.html#vs20", 22)
                || isValidVerse(curFile, vs, "Judg-19.html#vs29")
                || isValidVerse(curFile, vs, "1Sam-05.html#vs6")
                || isValidVerse(curFile, vs, "1Sam-06.html#vs9", 12)
                || isValidVerse(curFile, vs, "1Sam-07.html#vs13", 14)
                || isValidVerse(curFile, vs, "1Sam-10.html#vs2")
                || isValidVerse(curFile, vs, "1Sam-11.html#vs3", 7)
                || isValidVerse(curFile, vs, "1Sam-13.html#vs18")
                || isValidVerse(curFile, vs, "1Sam-27.html#vs1")
                || isValidVerse(curFile, vs, "1Sam-30.html#vs16")
                || isValidVerse(curFile, vs, "2Sam-07.html#vs10")
                || isValidVerse(curFile, vs, "2Sam-20.html#vs14")
                || isValidVerse(curFile, vs, "2Sam-21.html#vs5")
                || isValidVerse(curFile, vs, "1Kgs-01.html#vs3")
                || isValidVerse(curFile, vs, "1Kgs-04.html#vs13")
                || isValidVerse(curFile, vs, "2Kgs-10.html#vs32")
                || isValidVerse(curFile, vs, "2Kgs-14.html#vs25")
                || isValidVerse(curFile, vs, "2Kgs-15.html#vs16")
                || isValidVerse(curFile, vs, "2Kgs-18.html#vs8")
                || isValidVerse(curFile, vs, "1Chr-04.html#vs10")
                || isValidVerse(curFile, vs, "1Chr-13.html#vs2")
                || isValidVerse(curFile, vs, "1Chr-16.html#vs18")
                || isValidVerse(curFile, vs, "1Chr-17.html#vs9")
                || isValidVerse(curFile, vs, "1Chr-21.html#vs12")
                || isValidVerse(curFile, vs, "2Chr-11.html#vs13")
                || isValidVerse(curFile, vs, "2Chr-26.html#vs6")
                || isValidVerse(curFile, vs, "2Chr-27.html#vs4")
                || isValidVerse(curFile, vs, "Ezra-04.html#vs10", 17)
                || isValidVerse(curFile, vs, "Ezra-05.html#vs3", 6)
                || isValidVerse(curFile, vs, "Ezra-06.html#vs6", 13)
                || isValidVerse(curFile, vs, "Ezra-08.html#vs36")
                || isValidVerse(curFile, vs, "Neh-02.html#vs7", 9)
                || isValidVerse(curFile, vs, "Neh-03.html#vs7", 22)
                || isValidVerse(curFile, vs, "Neh-12.html#vs28")
                || isValidVerse(curFile, vs, "Job-38.html#vs20", 27)
                || isValidVerse(curFile, vs, "Ps-078.html#vs12", 43)
                || isValidVerse(curFile, vs, "Ps-105.html#vs11", 31, 33)
                || isValidVerse(curFile, vs, "Ps-147.html#vs14")
                || isValidVerse(curFile, vs, "Isa-15.html#vs8")
                || isValidVerse(curFile, vs, "Jer-15.html#vs13")
                || isValidVerse(curFile, vs, "Jer-17.html#vs3")
                || isValidVerse(curFile, vs, "Jer-31.html#vs17")
                || isValidVerse(curFile, vs, "Ezek-25.html#vs5", 10)
                || isValidVerse(curFile, vs, "Ezek-34.html#vs26")
                || isValidVerse(curFile, vs, "Ezek-41.html#vs11")
                || isValidVerse(curFile, vs, "Ezek-43.html#vs12")
                || isValidVerse(curFile, vs, "Ezek-45.html#vs1", 7)
                || isValidVerse(curFile, vs, "Ezek-47.html#vs8", 13)
                || isValidVerse(curFile, vs, "Ezek-48.html#vs1", 2, 3, 4, 5, 6, 7, 8, 12, 13, 15)
                || isValidVerse(curFile, vs, "Ezek-48.html#vs21", 22, 23, 24, 25, 26, 27, 28)
                || isValidVerse(curFile, vs, "Hos-12.html#vs13")
                || isValidVerse(curFile, vs, "Joel-3.html#vs4", 6)
                || isValidVerse(curFile, vs, "Amos-1.html#vs13")
                || isValidVerse(curFile, vs, "Amos-6.html#vs2")
                || isValidVerse(curFile, vs, "Obad-1.html#vs19")
                || isValidVerse(curFile, vs, "Mic-5.html#vs5")
                || isValidVerse(curFile, vs, "Zeph-2.html#vs5", 6, 7, 8)
                || isValidVerse(curFile, vs, "Mal-1.html#vs4")
                || isValidVerse(curFile, vs, "Matt-02.html#vs16", 22)
                || isValidVerse(curFile, vs, "Matt-04.html#vs13", 15)
                || isValidVerse(curFile, vs, "Matt-08.html#vs34")
                || isValidVerse(curFile, vs, "Matt-09.html#vs26", 31)
                || isValidVerse(curFile, vs, "Matt-15.html#vs21", 39)
                || isValidVerse(curFile, vs, "Matt-16.html#vs13")
                || isValidVerse(curFile, vs, "Matt-19.html#vs1")
                || isValidVerse(curFile, vs, "Mark-05.html#vs17", 20)
                || isValidVerse(curFile, vs, "Mark-07.html#vs24", 31)
                || isValidVerse(curFile, vs, "Mark-10.html#vs1")
                || isValidVerse(curFile, vs, "Acts-13.html#vs50")
                || isValidVerse(curFile, vs, "Acts-18.html#vs24")
                || isValidVerse(curFile, vs, "2Cor-10.html#vs16")
                || isValidVerse(curFile, vs, "1Tim-4.html#vs15");
    } // isGebied

    public static boolean isGebod(final File curFile, final String vs, final @NotNull String arg) {
        if (arg.equals("gebod")) {
            return true;
        }
        return isValidVerse(curFile, vs, "Gen-26.html#vs5")
                || isValidVerse(curFile, vs, "Exod-15.html#vs26")
                || isValidVerse(curFile, vs, "Exod-16.html#vs28")
                || isValidVerse(curFile, vs, "Exod-20.html#vs6")
                || isValidVerse(curFile, vs, "Exod-24.html#vs12")
                || isValidVerse(curFile, vs, "Lev-04.html#vs2")
                || isValidVerse(curFile, vs, "Lev-04.html#vs22")
                || isValidVerse(curFile, vs, "Lev-04.html#vs27")
                || isValidVerse(curFile, vs, "Lev-05.html#vs17")
                || isValidVerse(curFile, vs, "Lev-22.html#vs31")
                || isValidVerse(curFile, vs, "Lev-26.html#vs3")
                || isValidVerse(curFile, vs, "Lev-26.html#vs14")
                || isValidVerse(curFile, vs, "Lev-26.html#vs15")
                || isValidVerse(curFile, vs, "Lev-27.html#vs34")
                || isValidVerse(curFile, vs, "Num-15.html#vs22")
                || isValidVerse(curFile, vs, "Num-15.html#vs39")
                || isValidVerse(curFile, vs, "Num-15.html#vs40")
                || isValidVerse(curFile, vs, "Num-36.html#vs13")
                || isValidVerse(curFile, vs, "Deut-04.html#vs2")
                || isValidVerse(curFile, vs, "Deut-04.html#vs40")
                || isValidVerse(curFile, vs, "Deut-05.html#vs10")
                || isValidVerse(curFile, vs, "Deut-05.html#vs29")
                || isValidVerse(curFile, vs, "Deut-05.html#vs31")
                || isValidVerse(curFile, vs, "Deut-06.html#vs1")
                || isValidVerse(curFile, vs, "Deut-06.html#vs2")
                || isValidVerse(curFile, vs, "Deut-06.html#vs17")
                || isValidVerse(curFile, vs, "Deut-06.html#vs25")
                || isValidVerse(curFile, vs, "Deut-07.html#vs9")
                || isValidVerse(curFile, vs, "Deut-07.html#vs11")
                || isValidVerse(curFile, vs, "Deut-08.html#vs1")
                || isValidVerse(curFile, vs, "Deut-08.html#vs2")
                || isValidVerse(curFile, vs, "Deut-08.html#vs6")
                || isValidVerse(curFile, vs, "Deut-08.html#vs11")
                || isValidVerse(curFile, vs, "Deut-10.html#vs13")
                || isValidVerse(curFile, vs, "Deut-11.html#vs1")
                || isValidVerse(curFile, vs, "Deut-11.html#vs8")
                || isValidVerse(curFile, vs, "Deut-11.html#vs13")
                || isValidVerse(curFile, vs, "Deut-11.html#vs22")
                || isValidVerse(curFile, vs, "Deut-11.html#vs27")
                || isValidVerse(curFile, vs, "Deut-11.html#vs28")
                || isValidVerse(curFile, vs, "Deut-13.html#vs4")
                || isValidVerse(curFile, vs, "Deut-13.html#vs18")
                || isValidVerse(curFile, vs, "Deut-15.html#vs5")
                || isValidVerse(curFile, vs, "Deut-15.html#vs5")
                || isValidVerse(curFile, vs, "Deut-26.html#vs17")
                || isValidVerse(curFile, vs, "Deut-26.html#vs18")
                || isValidVerse(curFile, vs, "Deut-27.html#vs1")
                || isValidVerse(curFile, vs, "Deut-27.html#vs10")
                || isValidVerse(curFile, vs, "Deut-28.html#vs1")
                || isValidVerse(curFile, vs, "Deut-28.html#vs9")
                || isValidVerse(curFile, vs, "Deut-28.html#vs13")
                || isValidVerse(curFile, vs, "Deut-28.html#vs15")
                || isValidVerse(curFile, vs, "Deut-28.html#vs45")
                || isValidVerse(curFile, vs, "Deut-30.html#vs8")
                || isValidVerse(curFile, vs, "Deut-30.html#vs10")
                || isValidVerse(curFile, vs, "Deut-30.html#vs16")
                || isValidVerse(curFile, vs, "Deut-31.html#vs5")
                || isValidVerse(curFile, vs, "Josh-22.html#vs2")
                || isValidVerse(curFile, vs, "Judg-02.html#vs17")
                || isValidVerse(curFile, vs, "Judg-03.html#vs4")
                || isValidVerse(curFile, vs, "1Kgs-02.html#vs3")
                || isValidVerse(curFile, vs, "1Kgs-03.html#vs14")
                || isValidVerse(curFile, vs, "1Kgs-06.html#vs12")
                || isValidVerse(curFile, vs, "1Kgs-08.html#vs58")
                || isValidVerse(curFile, vs, "1Kgs-08.html#vs61")
                || isValidVerse(curFile, vs, "1Kgs-09.html#vs6")
                || isValidVerse(curFile, vs, "1Kgs-11.html#vs34")
                || isValidVerse(curFile, vs, "1Kgs-11.html#vs38")
                || isValidVerse(curFile, vs, "1Kgs-14.html#vs8")
                || isValidVerse(curFile, vs, "1Kgs-18.html#vs18")
                || isValidVerse(curFile, vs, "2Kgs-17.html#vs13")
                || isValidVerse(curFile, vs, "2Kgs-17.html#vs16")
                || isValidVerse(curFile, vs, "2Kgs-17.html#vs19")
                || isValidVerse(curFile, vs, "2Kgs-17.html#vs37")
                || isValidVerse(curFile, vs, "2Kgs-18.html#vs6")
                || isValidVerse(curFile, vs, "2Kgs-23.html#vs3")
                || isValidVerse(curFile, vs, "1Chr-28.html#vs7")
                || isValidVerse(curFile, vs, "1Chr-28.html#vs8")
                || isValidVerse(curFile, vs, "1Chr-29.html#vs19")
                || isValidVerse(curFile, vs, "2Chr-07.html#vs19")
                || isValidVerse(curFile, vs, "2Chr-17.html#vs4")
                || isValidVerse(curFile, vs, "2Chr-24.html#vs20")
                || isValidVerse(curFile, vs, "2Chr-34.html#vs31")
                || isValidVerse(curFile, vs, "Ezra-07.html#vs11")
                || isValidVerse(curFile, vs, "Ezra-09.html#vs10")
                || isValidVerse(curFile, vs, "Ezra-09.html#vs14")
                || isValidVerse(curFile, vs, "Neh-01.html#vs5")
                || isValidVerse(curFile, vs, "Neh-01.html#vs7")
                || isValidVerse(curFile, vs, "Neh-01.html#vs9")
                || isValidVerse(curFile, vs, "Neh-09.html#vs13")
                || isValidVerse(curFile, vs, "Neh-09.html#vs14")
                || isValidVerse(curFile, vs, "Neh-09.html#vs16")
                || isValidVerse(curFile, vs, "Neh-09.html#vs29")
                || isValidVerse(curFile, vs, "Neh-09.html#vs34")
                || isValidVerse(curFile, vs, "Neh-10.html#vs29")
                || isValidVerse(curFile, vs, "Neh-10.html#vs32")
                || isValidVerse(curFile, vs, "Ps-078.html#vs7")
                || isValidVerse(curFile, vs, "Ps-089.html#vs32")
                || isValidVerse(curFile, vs, "Ps-112.html#vs1")
                || isValidVerse(curFile, vs, "Ps-119.html#vs6")
                || isValidVerse(curFile, vs, "Ps-119.html#vs10")
                || isValidVerse(curFile, vs, "Ps-119.html#vs19")
                || isValidVerse(curFile, vs, "Ps-119.html#vs21")
                || isValidVerse(curFile, vs, "Ps-119.html#vs32")
                || isValidVerse(curFile, vs, "Ps-119.html#vs35")
                || isValidVerse(curFile, vs, "Ps-119.html#vs47")
                || isValidVerse(curFile, vs, "Ps-119.html#vs48")
                || isValidVerse(curFile, vs, "Ps-119.html#vs60")
                || isValidVerse(curFile, vs, "Ps-119.html#vs66")
                || isValidVerse(curFile, vs, "Ps-119.html#vs73")
                || isValidVerse(curFile, vs, "Ps-119.html#vs86")
                || isValidVerse(curFile, vs, "Ps-119.html#vs98")
                || isValidVerse(curFile, vs, "Ps-119.html#vs115")
                || isValidVerse(curFile, vs, "Ps-119.html#vs127")
                || isValidVerse(curFile, vs, "Ps-119.html#vs131")
                || isValidVerse(curFile, vs, "Ps-119.html#vs143")
                || isValidVerse(curFile, vs, "Ps-119.html#vs151")
                || isValidVerse(curFile, vs, "Ps-119.html#vs166")
                || isValidVerse(curFile, vs, "Ps-119.html#vs172")
                || isValidVerse(curFile, vs, "Ps-119.html#vs176")
                || isValidVerse(curFile, vs, "Prov-02.html#vs1")
                || isValidVerse(curFile, vs, "Prov-03.html#vs1")
                || isValidVerse(curFile, vs, "Prov-04.html#vs4")
                || isValidVerse(curFile, vs, "Prov-07.html#vs1")
                || isValidVerse(curFile, vs, "Prov-07.html#vs2")
                || isValidVerse(curFile, vs, "Prov-10.html#vs8")
                || isValidVerse(curFile, vs, "Eccl-12.html#vs13")
                || isValidVerse(curFile, vs, "Isa-48.html#vs18")
                || isValidVerse(curFile, vs, "Jer-35.html#vs18")
                || isValidVerse(curFile, vs, "Dan-09.html#vs4")
                || isValidVerse(curFile, vs, "Dan-09.html#vs5")
                || isValidVerse(curFile, vs, "Matt-05.html#vs19")
                || isValidVerse(curFile, vs, "Matt-15.html#vs9")
                || isValidVerse(curFile, vs, "Matt-19.html#vs17")
                || isValidVerse(curFile, vs, "Matt-22.html#vs40")
                || isValidVerse(curFile, vs, "Mark-07.html#vs7")
                || isValidVerse(curFile, vs, "Mark-10.html#vs19")
                || isValidVerse(curFile, vs, "Mark-12.html#vs28")
                || isValidVerse(curFile, vs, "Mark-12.html#vs29")
                || isValidVerse(curFile, vs, "Luke-01.html#vs6")
                || isValidVerse(curFile, vs, "Luke-18.html#vs20")
                || isValidVerse(curFile, vs, "John-14.html#vs15")
                || isValidVerse(curFile, vs, "John-14.html#vs21")
                || isValidVerse(curFile, vs, "John-15.html#vs10")
                || isValidVerse(curFile, vs, "Acts-17.html#vs7")
                || isValidVerse(curFile, vs, "1Cor-07.html#vs19")
                || isValidVerse(curFile, vs, "1Cor-14.html#vs37")
                || isValidVerse(curFile, vs, "Eph-2.html#vs15")
                || isValidVerse(curFile, vs, "Col-2.html#vs22")
                || isValidVerse(curFile, vs, "Titus-1.html#vs14")
                || isValidVerse(curFile, vs, "Jas-2.html#vs10")
                || isValidVerse(curFile, vs, "1John-2.html#vs3")
                || isValidVerse(curFile, vs, "1John-2.html#vs4")
                || isValidVerse(curFile, vs, "1John-3.html#vs22")
                || isValidVerse(curFile, vs, "1John-3.html#vs24")
                || isValidVerse(curFile, vs, "1John-5.html#vs2")
                || isValidVerse(curFile, vs, "1John-5.html#vs3")
                || isValidVerse(curFile, vs, "2John-1.html#vs6")
                || isValidVerse(curFile, vs, "Rev-12.html#vs17")
                || isValidVerse(curFile, vs, "Rev-14.html#vs12")
                || isValidVerse(curFile, vs, "Rev-22.html#vs14")
                || isValidVerse(curFile, vs, "Didache-04.html#vs13");
    } // isGebod

    public static boolean isGebieden(final File curFile, final String vs, final String arg) {
        return (!isGebod(curFile, vs, arg)
                && !isGebied(curFile, vs))
                || isZowelGebiedAlsGebieden(curFile, vs);
    } // isGebieden
}
