package rb.hsv.appendix;

public class Constants {
    public final static String ROOT = "C:\\Temp\\hsv met bijlagen\\content\\OPS";
    public final static String VERSES = "C:\\Temp\\hsv met bijlagen\\verses.txt";
    public final static String RESULT = "C:\\Temp\\hsv met bijlagen\\result.txt";
    public final static String RESULT_CCD = "C:\\Temp\\hsv met bijlagen\\result-ccd.txt";
    public final static String APPENDIX = "C:\\Temp\\hsv met bijlagen\\appendix.txt";
    public final static String TEXTONLY_DIR = "C:\\Temp\\hsv met bijlagen\\textOnly";
    public final static String CONCORDANTIE = "c:\\data\\source\\appendix\\src\\main\\resources\\text\\concordantie.txt";
    public final static String CONCORDANTIE_DEV = "c:\\data\\source\\appendix\\src\\main\\resources\\text\\concordantie-dev.txt";

    //public final static String ROOT = "C:\\test\\hsv";
    public final static String GEN = "Gen. ";
    public final static String EXOD = "Ex. ";
    public final static String LEV = "Lev. ";
    public final static String NUM = "Num. ";
    public final static String DEUT = "Deut. ";
    public final static String JOZ = "Joz. ";
    public final static String RICHT = "Richt. ";
    public final static String RUTH = "Ruth ";
    public final static String SAM_1 = "1 Sam. ";
    public final static String SAM_2 = "2 Sam. ";
    public final static String KON_1 = "1 Kon. ";
    public final static String KON_2 = "2 Kon. ";
    public final static String KRON_1 = "1 Kron. ";
    public final static String KRON_2 = "2 Kron. ";
    public final static String EZRA = "Ezra ";
    public final static String NEH = "Neh. ";
    public final static String ESTH = "Esth. ";
    public final static String JOB = "Job ";
    public final static String PS = "Ps. ";
    public final static String SPR = "Spr. ";
    public final static String PRED = "Pred. ";
    public final static String HOOGL = "Hoogl. ";
    public final static String JES = "Jes. ";
    public final static String JER = "Jer. ";
    public final static String KLAAGL = "Klaagl. ";
    public final static String EZECH = "Ezech. ";
    public final static String DAN = "Dan. ";
    public final static String HOS = "Hos. ";
    public final static String JOEL = "Jo&#235;l ";
    public final static String AMOS = "Amos ";
    public final static String OBADJA = "Obadja ";
    public final static String JONA = "Jona ";
    public final static String MICHA = "Micha ";
    public final static String NAHUM = "Nahum ";
    public final static String HAB = "Hab. ";
    public final static String ZEF = "Zef. ";
    public final static String HAGGAI = "Hagga&#239; ";
    public final static String ZACH = "Zach. ";
    public final static String MAL = "Mal. ";
    public final static String MATT = "Matt. ";
    public final static String MARK = "Mark. ";
    public final static String LUK = "Luk. ";
    public final static String JOH = "Joh. ";
    public final static String HAND = "Hand. ";
    public final static String ROM = "Rom. ";
    public final static String KOR_1 = "1 Kor. ";
    public final static String KOR_2 = "2 Kor. ";
    public final static String GAL = "Gal. ";
    public final static String EFEZ = "Efez. ";
    public final static String FILIPP = "Filipp. ";
    public final static String KOL = "Kol. ";
    public final static String THESS_1 = "1 Thess. ";
    public final static String THESS_2 = "2 Thess. ";
    public final static String TIM_1 = "1 Tim. ";
    public final static String TIM_2 = "2 Tim. ";
    public final static String TIT = "Tit. ";
    public final static String FILEM = "Filem. ";
    public final static String HEBR = "Hebr. ";
    public final static String JAK = "Jak. ";
    public final static String PETR_1 = "1 Petr. ";
    public final static String PETR_2 = "2 Petr. ";
    public final static String JOH_1 = "1 Joh. ";
    public final static String JOH_2 = "2 Joh. ";
    public final static String JOH_3 = "3 Joh. ";
    public final static String JUDAS = "Judas ";
    public final static String OPENB = "Openb. ";
    public final static String DIDACHE = "Didache ";

    public final static String PERICOPE = "class=\"pericope\"";
    public final static String PERICOPE_TAG = "<h3 class=\"pericope\">";
    public final static String HREF = "<a class=\"appendix\" href=\"";
    public final static String HREF_PERICOPE = "<a class=\"appendix-pc\" href=\"";


    public final static String[] EXTENSIONS = new String[] {"html"};
}
