package rb.hsv.appendix.ccd.valid.util;

public enum Books {
    GEN("Gen"),
    EXOD("Exod"),
    LEV("Lev"),
    NUM("Num"),
    DEUT("Deut"),
    JOSH("Josh"),
    JUDG("Judg"),
    RUTH("Ruth"),
    SAM_1("1Sam"),
    SAM_2("2Sam"),
    KON_1("1Kgs"),
    KON_2("2Kgs"),
    KRON_1("1Chr"),
    KRON_2("2Chr"),
    EZRA("Ezra"),
    NEH("Neh"),
    ESTH("Esth"),
    JOB("Job"),
    PS("Ps"),
    PROV("Prov"),
    ECCL("Eccl"),
    SONG("Song"),
    ISA("Isa"),
    JER("Jer"),
    LAM("Lam"),
    EZEK("Ezek"),
    DAN("Dan"),
    HOS("Hos"),
    JOEL("Joel"),
    AMOS("Amos"),
    OBAD("Obad"),
    JONAH("Jonah"),
    MIC("Mic"),
    NAH("Nah"),
    HAB("Hab"),
    ZEPH("Zeph"),
    HAG("Hag"),
    ZECH("Zech"),
    MAL("Mal"),
    MATT("Matt"),
    MARK("Mark"),
    LUKE("Luke"),
    JOHN("John"),
    ACTS("Acts"),
    ROM("Rom"),
    COR_1("1Cor"),
    COR_2("2Cor"),
    GAL("Gal"),
    EPH("Eph"),
    PHIL("Phil"),
    COL("Col"),
    THESS_1("1Thess"),
    THESS_2("2Thess"),
    TIM_1("1Tim"),
    TIM_2("2Tim"),
    TITUS("Titus"),
    PHLM("Phlm"),
    HEB("Heb"),
    JAS("Jas"),
    PET_1("1Pet"),
    PET_2("2Pet"),
    JOHN_1("1John"),
    JOHN_2("2John"),
    JOHN_3("3John"),
    JUDE("Jude"),
    REV("Rev"),
    DIDACHE("Didache"),;

    public final String value;

    Books(String value) {
        this.value = value;
    }
}
